apiVersion: kms.gcp.jet.crossplane.io/v1alpha1
kind: SecretCiphertext
metadata:
  name: example
spec:
  forProvider:
    cryptoKey: ${google_kms_crypto_key.cryptokey.id}
    plaintextSecretRef:
      key: example-key
      name: example-secret
      namespace: crossplane-system
  providerConfigRef:
    name: example
