apiVersion: pubsub.gcp.jet.crossplane.io/v1alpha1
kind: LiteReservation
metadata:
  name: example
spec:
  forProvider:
    name: example-reservation
    project: ${data.google_project.project.number}
    throughputCapacity: 2
  providerConfigRef:
    name: example
