apiVersion: accesscontextmanager.gcp.jet.crossplane.io/v1alpha1
kind: AccessPolicy
metadata:
  name: example
spec:
  forProvider:
    parent: organizations/123456789
    title: my policy
  providerConfigRef:
    name: example
