apiVersion: accesscontextmanager.gcp.jet.crossplane.io/v1alpha1
kind: ServicePerimeter
metadata:
  name: example
spec:
  forProvider:
    name: accessPolicies/${google_access_context_manager_access_policy.access-policy.name}/servicePerimeters/restrict_storage
    parent: accessPolicies/${google_access_context_manager_access_policy.access-policy.name}
    status:
    - restrictedServices:
      - storage.googleapis.com
    title: restrict_storage
  providerConfigRef:
    name: example
