/*
Copyright 2021 The Crossplane Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by terrajet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/apis/common/v1"
)

type ClusterSelectorObservation struct {
}

type ClusterSelectorParameters struct {

	// Required. The cluster labels. Cluster must have all labels to match.
	// +kubebuilder:validation:Required
	ClusterLabels map[string]*string `json:"clusterLabels" tf:"cluster_labels,omitempty"`

	// Optional. The zone where workflow process executes. This parameter does not affect the selection of the cluster. If unspecified, the zone of the first cluster matching the selector is used.
	// +kubebuilder:validation:Optional
	Zone *string `json:"zone,omitempty" tf:"zone,omitempty"`
}

type ConfigAutoscalingConfigObservation struct {
}

type ConfigAutoscalingConfigParameters struct {

	// Optional. The autoscaling policy used by the cluster. Only resource names including projectid and location (region) are valid. Examples: * `https://www.googleapis.com/compute/v1/projects/[project_id]/locations/[dataproc_region]/autoscalingPolicies/[policy_id]` * `projects/[project_id]/locations/[dataproc_region]/autoscalingPolicies/[policy_id]` Note that the policy must be in the same project and Dataproc region.
	// +kubebuilder:validation:Optional
	Policy *string `json:"policy,omitempty" tf:"policy,omitempty"`
}

type ConfigEncryptionConfigObservation struct {
}

type ConfigEncryptionConfigParameters struct {

	// Optional. The Cloud KMS key name to use for PD disk encryption for all instances in the cluster.
	// +kubebuilder:validation:Optional
	GcePdKmsKeyName *string `json:"gcePdKmsKeyName,omitempty" tf:"gce_pd_kms_key_name,omitempty"`
}

type ConfigGceClusterConfigObservation struct {
}

type ConfigGceClusterConfigParameters struct {

	// Optional. If true, all instances in the cluster will only have internal IP addresses. By default, clusters are not restricted to internal IP addresses, and will have ephemeral external IP addresses assigned to each instance. This `internal_ip_only` restriction can only be enabled for subnetwork enabled networks, and all off-cluster dependencies must be configured to be accessible without external IP addresses.
	// +kubebuilder:validation:Optional
	InternalIPOnly *bool `json:"internalIpOnly,omitempty" tf:"internal_ip_only,omitempty"`

	// The Compute Engine metadata entries to add to all instances (see [Project and instance metadata](https://cloud.google.com/compute/docs/storing-retrieving-metadata#project_and_instance_metadata)).
	// +kubebuilder:validation:Optional
	Metadata map[string]*string `json:"metadata,omitempty" tf:"metadata,omitempty"`

	// Optional. The Compute Engine network to be used for machine communications. Cannot be specified with subnetwork_uri. If neither `network_uri` nor `subnetwork_uri` is specified, the "default" network of the project is used, if it exists. Cannot be a "Custom Subnet Network" (see [Using Subnetworks](https://cloud.google.com/compute/docs/subnetworks) for more information). A full URL, partial URI, or short name are valid. Examples: * `https://www.googleapis.com/compute/v1/projects/[project_id]/regions/global/default` * `projects/[project_id]/regions/global/default` * `default`
	// +kubebuilder:validation:Optional
	Network *string `json:"network,omitempty" tf:"network,omitempty"`

	// Optional. Node Group Affinity for sole-tenant clusters.
	// +kubebuilder:validation:Optional
	NodeGroupAffinity []NodeGroupAffinityParameters `json:"nodeGroupAffinity,omitempty" tf:"node_group_affinity,omitempty"`

	// Optional. The type of IPv6 access for a cluster. Possible values: PRIVATE_IPV6_GOOGLE_ACCESS_UNSPECIFIED, INHERIT_FROM_SUBNETWORK, OUTBOUND, BIDIRECTIONAL
	// +kubebuilder:validation:Optional
	PrivateIPv6GoogleAccess *string `json:"privateIpv6GoogleAccess,omitempty" tf:"private_ipv6_google_access,omitempty"`

	// Optional. Reservation Affinity for consuming Zonal reservation.
	// +kubebuilder:validation:Optional
	ReservationAffinity []ReservationAffinityParameters `json:"reservationAffinity,omitempty" tf:"reservation_affinity,omitempty"`

	// Optional. The [Dataproc service account](https://cloud.google.com/dataproc/docs/concepts/configuring-clusters/service-accounts#service_accounts_in_dataproc) (also see [VM Data Plane identity](https://cloud.google.com/dataproc/docs/concepts/iam/dataproc-principals#vm_service_account_data_plane_identity)) used by Dataproc cluster VM instances to access Google Cloud Platform services. If not specified, the [Compute Engine default service account](https://cloud.google.com/compute/docs/access/service-accounts#default_service_account) is used.
	// +kubebuilder:validation:Optional
	ServiceAccount *string `json:"serviceAccount,omitempty" tf:"service_account,omitempty"`

	// Optional. The URIs of service account scopes to be included in Compute Engine instances. The following base set of scopes is always included: * https://www.googleapis.com/auth/cloud.useraccounts.readonly * https://www.googleapis.com/auth/devstorage.read_write * https://www.googleapis.com/auth/logging.write If no scopes are specified, the following defaults are also provided: * https://www.googleapis.com/auth/bigquery * https://www.googleapis.com/auth/bigtable.admin.table * https://www.googleapis.com/auth/bigtable.data * https://www.googleapis.com/auth/devstorage.full_control
	// +kubebuilder:validation:Optional
	ServiceAccountScopes []*string `json:"serviceAccountScopes,omitempty" tf:"service_account_scopes,omitempty"`

	// Optional. The Compute Engine subnetwork to be used for machine communications. Cannot be specified with network_uri. A full URL, partial URI, or short name are valid. Examples: * `https://www.googleapis.com/compute/v1/projects/[project_id]/regions/us-east1/subnetworks/sub0` * `projects/[project_id]/regions/us-east1/subnetworks/sub0` * `sub0`
	// +kubebuilder:validation:Optional
	Subnetwork *string `json:"subnetwork,omitempty" tf:"subnetwork,omitempty"`

	// The Compute Engine tags to add to all instances (see [Tagging instances](https://cloud.google.com/compute/docs/label-or-tag-resources#tags)).
	// +kubebuilder:validation:Optional
	Tags []*string `json:"tags,omitempty" tf:"tags,omitempty"`

	// Optional. The zone where the Compute Engine cluster will be located. On a create request, it is required in the "global" region. If omitted in a non-global Dataproc region, the service will pick a zone in the corresponding Compute Engine region. On a get request, zone will always be present. A full URL, partial URI, or short name are valid. Examples: * `https://www.googleapis.com/compute/v1/projects/[project_id]/zones/[zone]` * `projects/[project_id]/zones/[zone]` * `us-central1-f`
	// +kubebuilder:validation:Optional
	Zone *string `json:"zone,omitempty" tf:"zone,omitempty"`
}

type ConfigMasterConfigObservation struct {
	InstanceNames []*string `json:"instanceNames,omitempty" tf:"instance_names,omitempty"`

	IsPreemptible *bool `json:"isPreemptible,omitempty" tf:"is_preemptible,omitempty"`

	ManagedGroupConfig []ManagedGroupConfigObservation `json:"managedGroupConfig,omitempty" tf:"managed_group_config,omitempty"`
}

type ConfigMasterConfigParameters struct {

	// Optional. The Compute Engine accelerator configuration for these instances.
	// +kubebuilder:validation:Optional
	Accelerators []MasterConfigAcceleratorsParameters `json:"accelerators,omitempty" tf:"accelerators,omitempty"`

	// Optional. Disk option config settings.
	// +kubebuilder:validation:Optional
	DiskConfig []MasterConfigDiskConfigParameters `json:"diskConfig,omitempty" tf:"disk_config,omitempty"`

	// Optional. The Compute Engine image resource used for cluster instances. The URI can represent an image or image family. Image examples: * `https://www.googleapis.com/compute/beta/projects/[project_id]/global/images/[image-id]` * `projects/[project_id]/global/images/[image-id]` * `image-id` Image family examples. Dataproc will use the most recent image from the family: * `https://www.googleapis.com/compute/beta/projects/[project_id]/global/images/family/[custom-image-family-name]` * `projects/[project_id]/global/images/family/[custom-image-family-name]` If the URI is unspecified, it will be inferred from `SoftwareConfig.image_version` or the system default.
	// +kubebuilder:validation:Optional
	Image *string `json:"image,omitempty" tf:"image,omitempty"`

	// Optional. The Compute Engine machine type used for cluster instances. A full URL, partial URI, or short name are valid. Examples: * `https://www.googleapis.com/compute/v1/projects/[project_id]/zones/us-east1-a/machineTypes/n1-standard-2` * `projects/[project_id]/zones/us-east1-a/machineTypes/n1-standard-2` * `n1-standard-2` **Auto Zone Exception**: If you are using the Dataproc [Auto Zone Placement](https://cloud.google.com/dataproc/docs/concepts/configuring-clusters/auto-zone#using_auto_zone_placement) feature, you must use the short name of the machine type resource, for example, `n1-standard-2`.
	// +kubebuilder:validation:Optional
	MachineType *string `json:"machineType,omitempty" tf:"machine_type,omitempty"`

	// Optional. Specifies the minimum cpu platform for the Instance Group. See [Dataproc -> Minimum CPU Platform](https://cloud.google.com/dataproc/docs/concepts/compute/dataproc-min-cpu).
	// +kubebuilder:validation:Optional
	MinCPUPlatform *string `json:"minCpuPlatform,omitempty" tf:"min_cpu_platform,omitempty"`

	// Optional. The number of VM instances in the instance group. For [HA cluster](/dataproc/docs/concepts/configuring-clusters/high-availability) [master_config](#FIELDS.master_config) groups, **must be set to 3**. For standard cluster [master_config](#FIELDS.master_config) groups, **must be set to 1**.
	// +kubebuilder:validation:Optional
	NumInstances *int64 `json:"numInstances,omitempty" tf:"num_instances,omitempty"`

	// Optional. Specifies the preemptibility of the instance group. The default value for master and worker groups is `NON_PREEMPTIBLE`. This default cannot be changed. The default value for secondary instances is `PREEMPTIBLE`. Possible values: PREEMPTIBILITY_UNSPECIFIED, NON_PREEMPTIBLE, PREEMPTIBLE
	// +kubebuilder:validation:Optional
	Preemptibility *string `json:"preemptibility,omitempty" tf:"preemptibility,omitempty"`
}

type ConfigObservation struct {
}

type ConfigParameters struct {

	// Optional. Autoscaling config for the policy associated with the cluster. Cluster does not autoscale if this field is unset.
	// +kubebuilder:validation:Optional
	AutoscalingConfig []ConfigAutoscalingConfigParameters `json:"autoscalingConfig,omitempty" tf:"autoscaling_config,omitempty"`

	// Optional. Encryption settings for the cluster.
	// +kubebuilder:validation:Optional
	EncryptionConfig []ConfigEncryptionConfigParameters `json:"encryptionConfig,omitempty" tf:"encryption_config,omitempty"`

	// Optional. Port/endpoint configuration for this cluster
	// +kubebuilder:validation:Optional
	EndpointConfig []EndpointConfigParameters `json:"endpointConfig,omitempty" tf:"endpoint_config,omitempty"`

	// Optional. The shared Compute Engine config settings for all instances in a cluster.
	// +kubebuilder:validation:Optional
	GceClusterConfig []ConfigGceClusterConfigParameters `json:"gceClusterConfig,omitempty" tf:"gce_cluster_config,omitempty"`

	// Optional. Commands to execute on each node after config is completed. By default, executables are run on master and all worker nodes. You can test a node's `role` metadata to run an executable on a master or worker node, as shown below using `curl` (you can also use `wget`): ROLE=$(curl -H Metadata-Flavor:Google http://metadata/computeMetadata/v1/instance/attributes/dataproc-role) if [[ "${ROLE}" == 'Master' ]]; then ... master specific actions ... else ... worker specific actions ... fi
	// +kubebuilder:validation:Optional
	InitializationActions []InitializationActionsParameters `json:"initializationActions,omitempty" tf:"initialization_actions,omitempty"`

	// Optional. Lifecycle setting for the cluster.
	// +kubebuilder:validation:Optional
	LifecycleConfig []LifecycleConfigParameters `json:"lifecycleConfig,omitempty" tf:"lifecycle_config,omitempty"`

	// Optional. The Compute Engine config settings for worker instances in a cluster.
	// +kubebuilder:validation:Optional
	MasterConfig []ConfigMasterConfigParameters `json:"masterConfig,omitempty" tf:"master_config,omitempty"`

	// Optional. The Compute Engine config settings for worker instances in a cluster.
	// +kubebuilder:validation:Optional
	SecondaryWorkerConfig []ConfigSecondaryWorkerConfigParameters `json:"secondaryWorkerConfig,omitempty" tf:"secondary_worker_config,omitempty"`

	// Optional. Security settings for the cluster.
	// +kubebuilder:validation:Optional
	SecurityConfig []ConfigSecurityConfigParameters `json:"securityConfig,omitempty" tf:"security_config,omitempty"`

	// Optional. The config settings for software inside the cluster.
	// +kubebuilder:validation:Optional
	SoftwareConfig []ConfigSoftwareConfigParameters `json:"softwareConfig,omitempty" tf:"software_config,omitempty"`

	// Optional. A Cloud Storage bucket used to stage job dependencies, config files, and job driver console output. If you do not specify a staging bucket, Cloud Dataproc will determine a Cloud Storage location (US, ASIA, or EU) for your cluster's staging bucket according to the Compute Engine zone where your cluster is deployed, and then create and manage this project-level, per-location bucket (see [Dataproc staging bucket](https://cloud.google.com/dataproc/docs/concepts/configuring-clusters/staging-bucket)). **This field requires a Cloud Storage bucket name, not a URI to a Cloud Storage bucket.**
	// +kubebuilder:validation:Optional
	StagingBucket *string `json:"stagingBucket,omitempty" tf:"staging_bucket,omitempty"`

	// Optional. A Cloud Storage bucket used to store ephemeral cluster and jobs data, such as Spark and MapReduce history files. If you do not specify a temp bucket, Dataproc will determine a Cloud Storage location (US, ASIA, or EU) for your cluster's temp bucket according to the Compute Engine zone where your cluster is deployed, and then create and manage this project-level, per-location bucket. The default bucket has a TTL of 90 days, but you can use any TTL (or none) if you specify a bucket. **This field requires a Cloud Storage bucket name, not a URI to a Cloud Storage bucket.**
	// +kubebuilder:validation:Optional
	TempBucket *string `json:"tempBucket,omitempty" tf:"temp_bucket,omitempty"`

	// Optional. The Compute Engine config settings for worker instances in a cluster.
	// +kubebuilder:validation:Optional
	WorkerConfig []ConfigWorkerConfigParameters `json:"workerConfig,omitempty" tf:"worker_config,omitempty"`
}

type ConfigSecondaryWorkerConfigObservation struct {
	InstanceNames []*string `json:"instanceNames,omitempty" tf:"instance_names,omitempty"`

	IsPreemptible *bool `json:"isPreemptible,omitempty" tf:"is_preemptible,omitempty"`

	ManagedGroupConfig []SecondaryWorkerConfigManagedGroupConfigObservation `json:"managedGroupConfig,omitempty" tf:"managed_group_config,omitempty"`
}

type ConfigSecondaryWorkerConfigParameters struct {

	// Optional. The Compute Engine accelerator configuration for these instances.
	// +kubebuilder:validation:Optional
	Accelerators []SecondaryWorkerConfigAcceleratorsParameters `json:"accelerators,omitempty" tf:"accelerators,omitempty"`

	// Optional. Disk option config settings.
	// +kubebuilder:validation:Optional
	DiskConfig []SecondaryWorkerConfigDiskConfigParameters `json:"diskConfig,omitempty" tf:"disk_config,omitempty"`

	// Optional. The Compute Engine image resource used for cluster instances. The URI can represent an image or image family. Image examples: * `https://www.googleapis.com/compute/beta/projects/[project_id]/global/images/[image-id]` * `projects/[project_id]/global/images/[image-id]` * `image-id` Image family examples. Dataproc will use the most recent image from the family: * `https://www.googleapis.com/compute/beta/projects/[project_id]/global/images/family/[custom-image-family-name]` * `projects/[project_id]/global/images/family/[custom-image-family-name]` If the URI is unspecified, it will be inferred from `SoftwareConfig.image_version` or the system default.
	// +kubebuilder:validation:Optional
	Image *string `json:"image,omitempty" tf:"image,omitempty"`

	// Optional. The Compute Engine machine type used for cluster instances. A full URL, partial URI, or short name are valid. Examples: * `https://www.googleapis.com/compute/v1/projects/[project_id]/zones/us-east1-a/machineTypes/n1-standard-2` * `projects/[project_id]/zones/us-east1-a/machineTypes/n1-standard-2` * `n1-standard-2` **Auto Zone Exception**: If you are using the Dataproc [Auto Zone Placement](https://cloud.google.com/dataproc/docs/concepts/configuring-clusters/auto-zone#using_auto_zone_placement) feature, you must use the short name of the machine type resource, for example, `n1-standard-2`.
	// +kubebuilder:validation:Optional
	MachineType *string `json:"machineType,omitempty" tf:"machine_type,omitempty"`

	// Optional. Specifies the minimum cpu platform for the Instance Group. See [Dataproc -> Minimum CPU Platform](https://cloud.google.com/dataproc/docs/concepts/compute/dataproc-min-cpu).
	// +kubebuilder:validation:Optional
	MinCPUPlatform *string `json:"minCpuPlatform,omitempty" tf:"min_cpu_platform,omitempty"`

	// Optional. The number of VM instances in the instance group. For [HA cluster](/dataproc/docs/concepts/configuring-clusters/high-availability) [master_config](#FIELDS.master_config) groups, **must be set to 3**. For standard cluster [master_config](#FIELDS.master_config) groups, **must be set to 1**.
	// +kubebuilder:validation:Optional
	NumInstances *int64 `json:"numInstances,omitempty" tf:"num_instances,omitempty"`

	// Optional. Specifies the preemptibility of the instance group. The default value for master and worker groups is `NON_PREEMPTIBLE`. This default cannot be changed. The default value for secondary instances is `PREEMPTIBLE`. Possible values: PREEMPTIBILITY_UNSPECIFIED, NON_PREEMPTIBLE, PREEMPTIBLE
	// +kubebuilder:validation:Optional
	Preemptibility *string `json:"preemptibility,omitempty" tf:"preemptibility,omitempty"`
}

type ConfigSecurityConfigObservation struct {
}

type ConfigSecurityConfigParameters struct {

	// Optional. Kerberos related configuration.
	// +kubebuilder:validation:Optional
	KerberosConfig []SecurityConfigKerberosConfigParameters `json:"kerberosConfig,omitempty" tf:"kerberos_config,omitempty"`
}

type ConfigSoftwareConfigObservation struct {
}

type ConfigSoftwareConfigParameters struct {

	// Optional. The version of software inside the cluster. It must be one of the supported [Dataproc Versions](https://cloud.google.com/dataproc/docs/concepts/versioning/dataproc-versions#supported_dataproc_versions), such as "1.2" (including a subminor version, such as "1.2.29"), or the ["preview" version](https://cloud.google.com/dataproc/docs/concepts/versioning/dataproc-versions#other_versions). If unspecified, it defaults to the latest Debian version.
	// +kubebuilder:validation:Optional
	ImageVersion *string `json:"imageVersion,omitempty" tf:"image_version,omitempty"`

	// Optional. The set of components to activate on the cluster.
	// +kubebuilder:validation:Optional
	OptionalComponents []*string `json:"optionalComponents,omitempty" tf:"optional_components,omitempty"`

	// Optional. The properties to set on daemon config files. Property keys are specified in `prefix:property` format, for example `core:hadoop.tmp.dir`. The following are supported prefixes and their mappings: * capacity-scheduler: `capacity-scheduler.xml` * core: `core-site.xml` * distcp: `distcp-default.xml` * hdfs: `hdfs-site.xml` * hive: `hive-site.xml` * mapred: `mapred-site.xml` * pig: `pig.properties` * spark: `spark-defaults.conf` * yarn: `yarn-site.xml` For more information, see [Cluster properties](https://cloud.google.com/dataproc/docs/concepts/cluster-properties).
	// +kubebuilder:validation:Optional
	Properties map[string]*string `json:"properties,omitempty" tf:"properties,omitempty"`
}

type ConfigWorkerConfigAcceleratorsObservation struct {
}

type ConfigWorkerConfigAcceleratorsParameters struct {

	// The number of the accelerator cards of this type exposed to this instance.
	// +kubebuilder:validation:Optional
	AcceleratorCount *int64 `json:"acceleratorCount,omitempty" tf:"accelerator_count,omitempty"`

	// Full URL, partial URI, or short name of the accelerator type resource to expose to this instance. See [Compute Engine AcceleratorTypes](https://cloud.google.com/compute/docs/reference/beta/acceleratorTypes). Examples: * `https://www.googleapis.com/compute/beta/projects/[project_id]/zones/us-east1-a/acceleratorTypes/nvidia-tesla-k80` * `projects/[project_id]/zones/us-east1-a/acceleratorTypes/nvidia-tesla-k80` * `nvidia-tesla-k80` **Auto Zone Exception**: If you are using the Dataproc [Auto Zone Placement](https://cloud.google.com/dataproc/docs/concepts/configuring-clusters/auto-zone#using_auto_zone_placement) feature, you must use the short name of the accelerator type resource, for example, `nvidia-tesla-k80`.
	// +kubebuilder:validation:Optional
	AcceleratorType *string `json:"acceleratorType,omitempty" tf:"accelerator_type,omitempty"`
}

type ConfigWorkerConfigDiskConfigObservation struct {
}

type ConfigWorkerConfigDiskConfigParameters struct {

	// Optional. Size in GB of the boot disk (default is 500GB).
	// +kubebuilder:validation:Optional
	BootDiskSizeGb *int64 `json:"bootDiskSizeGb,omitempty" tf:"boot_disk_size_gb,omitempty"`

	// Optional. Type of the boot disk (default is "pd-standard"). Valid values: "pd-balanced" (Persistent Disk Balanced Solid State Drive), "pd-ssd" (Persistent Disk Solid State Drive), or "pd-standard" (Persistent Disk Hard Disk Drive). See [Disk types](https://cloud.google.com/compute/docs/disks#disk-types).
	// +kubebuilder:validation:Optional
	BootDiskType *string `json:"bootDiskType,omitempty" tf:"boot_disk_type,omitempty"`

	// Optional. Number of attached SSDs, from 0 to 4 (default is 0). If SSDs are not attached, the boot disk is used to store runtime logs and [HDFS](https://hadoop.apache.org/docs/r1.2.1/hdfs_user_guide.html) data. If one or more SSDs are attached, this runtime bulk data is spread across them, and the boot disk contains only basic config and installed binaries.
	// +kubebuilder:validation:Optional
	NumLocalSsds *int64 `json:"numLocalSsds,omitempty" tf:"num_local_ssds,omitempty"`
}

type ConfigWorkerConfigObservation struct {
	InstanceNames []*string `json:"instanceNames,omitempty" tf:"instance_names,omitempty"`

	IsPreemptible *bool `json:"isPreemptible,omitempty" tf:"is_preemptible,omitempty"`

	ManagedGroupConfig []WorkerConfigManagedGroupConfigObservation `json:"managedGroupConfig,omitempty" tf:"managed_group_config,omitempty"`
}

type ConfigWorkerConfigParameters struct {

	// Optional. The Compute Engine accelerator configuration for these instances.
	// +kubebuilder:validation:Optional
	Accelerators []ConfigWorkerConfigAcceleratorsParameters `json:"accelerators,omitempty" tf:"accelerators,omitempty"`

	// Optional. Disk option config settings.
	// +kubebuilder:validation:Optional
	DiskConfig []ConfigWorkerConfigDiskConfigParameters `json:"diskConfig,omitempty" tf:"disk_config,omitempty"`

	// Optional. The Compute Engine image resource used for cluster instances. The URI can represent an image or image family. Image examples: * `https://www.googleapis.com/compute/beta/projects/[project_id]/global/images/[image-id]` * `projects/[project_id]/global/images/[image-id]` * `image-id` Image family examples. Dataproc will use the most recent image from the family: * `https://www.googleapis.com/compute/beta/projects/[project_id]/global/images/family/[custom-image-family-name]` * `projects/[project_id]/global/images/family/[custom-image-family-name]` If the URI is unspecified, it will be inferred from `SoftwareConfig.image_version` or the system default.
	// +kubebuilder:validation:Optional
	Image *string `json:"image,omitempty" tf:"image,omitempty"`

	// Optional. The Compute Engine machine type used for cluster instances. A full URL, partial URI, or short name are valid. Examples: * `https://www.googleapis.com/compute/v1/projects/[project_id]/zones/us-east1-a/machineTypes/n1-standard-2` * `projects/[project_id]/zones/us-east1-a/machineTypes/n1-standard-2` * `n1-standard-2` **Auto Zone Exception**: If you are using the Dataproc [Auto Zone Placement](https://cloud.google.com/dataproc/docs/concepts/configuring-clusters/auto-zone#using_auto_zone_placement) feature, you must use the short name of the machine type resource, for example, `n1-standard-2`.
	// +kubebuilder:validation:Optional
	MachineType *string `json:"machineType,omitempty" tf:"machine_type,omitempty"`

	// Optional. Specifies the minimum cpu platform for the Instance Group. See [Dataproc -> Minimum CPU Platform](https://cloud.google.com/dataproc/docs/concepts/compute/dataproc-min-cpu).
	// +kubebuilder:validation:Optional
	MinCPUPlatform *string `json:"minCpuPlatform,omitempty" tf:"min_cpu_platform,omitempty"`

	// Optional. The number of VM instances in the instance group. For [HA cluster](/dataproc/docs/concepts/configuring-clusters/high-availability) [master_config](#FIELDS.master_config) groups, **must be set to 3**. For standard cluster [master_config](#FIELDS.master_config) groups, **must be set to 1**.
	// +kubebuilder:validation:Optional
	NumInstances *int64 `json:"numInstances,omitempty" tf:"num_instances,omitempty"`

	// Optional. Specifies the preemptibility of the instance group. The default value for master and worker groups is `NON_PREEMPTIBLE`. This default cannot be changed. The default value for secondary instances is `PREEMPTIBLE`. Possible values: PREEMPTIBILITY_UNSPECIFIED, NON_PREEMPTIBLE, PREEMPTIBLE
	// +kubebuilder:validation:Optional
	Preemptibility *string `json:"preemptibility,omitempty" tf:"preemptibility,omitempty"`
}

type EndpointConfigObservation struct {
	HTTPPorts map[string]*string `json:"httpPorts,omitempty" tf:"http_ports,omitempty"`
}

type EndpointConfigParameters struct {

	// Optional. If true, enable http access to specific ports on the cluster from external sources. Defaults to false.
	// +kubebuilder:validation:Optional
	EnableHTTPPortAccess *bool `json:"enableHttpPortAccess,omitempty" tf:"enable_http_port_access,omitempty"`
}

type HadoopJobLoggingConfigObservation struct {
}

type HadoopJobLoggingConfigParameters struct {

	// The per-package log levels for the driver. This may include "root" package name to configure rootLogger. Examples: 'com.google = FATAL', 'root = INFO', 'org.apache = DEBUG'
	// +kubebuilder:validation:Optional
	DriverLogLevels map[string]*string `json:"driverLogLevels,omitempty" tf:"driver_log_levels,omitempty"`
}

type HadoopJobObservation struct {
}

type HadoopJobParameters struct {

	// Optional. HCFS URIs of archives to be extracted in the working directory of Hadoop drivers and tasks. Supported file types: .jar, .tar, .tar.gz, .tgz, or .zip.
	// +kubebuilder:validation:Optional
	ArchiveUris []*string `json:"archiveUris,omitempty" tf:"archive_uris,omitempty"`

	// Optional. The arguments to pass to the driver. Do not include arguments, such as `-libjars` or `-Dfoo=bar`, that can be set as job properties, since a collision may occur that causes an incorrect job submission.
	// +kubebuilder:validation:Optional
	Args []*string `json:"args,omitempty" tf:"args,omitempty"`

	// Optional. HCFS (Hadoop Compatible Filesystem) URIs of files to be copied to the working directory of Hadoop drivers and distributed tasks. Useful for naively parallel tasks.
	// +kubebuilder:validation:Optional
	FileUris []*string `json:"fileUris,omitempty" tf:"file_uris,omitempty"`

	// Optional. Jar file URIs to add to the CLASSPATHs of the Hadoop driver and tasks.
	// +kubebuilder:validation:Optional
	JarFileUris []*string `json:"jarFileUris,omitempty" tf:"jar_file_uris,omitempty"`

	// Optional. The runtime log config for job execution.
	// +kubebuilder:validation:Optional
	LoggingConfig []HadoopJobLoggingConfigParameters `json:"loggingConfig,omitempty" tf:"logging_config,omitempty"`

	// The name of the driver's main class. The jar file containing the class must be in the default CLASSPATH or specified in `jar_file_uris`.
	// +kubebuilder:validation:Optional
	MainClass *string `json:"mainClass,omitempty" tf:"main_class,omitempty"`

	// The HCFS URI of the jar file containing the main class. Examples: 'gs://foo-bucket/analytics-binaries/extract-useful-metrics-mr.jar' 'hdfs:/tmp/test-samples/custom-wordcount.jar' 'file:///home/usr/lib/hadoop-mapreduce/hadoop-mapreduce-examples.jar'
	// +kubebuilder:validation:Optional
	MainJarFileURI *string `json:"mainJarFileUri,omitempty" tf:"main_jar_file_uri,omitempty"`

	// Optional. A mapping of property names to values, used to configure Hadoop. Properties that conflict with values set by the Dataproc API may be overwritten. Can include properties set in /etc/hadoop/conf/*-site and classes in user code.
	// +kubebuilder:validation:Optional
	Properties map[string]*string `json:"properties,omitempty" tf:"properties,omitempty"`
}

type HiveJobObservation struct {
}

type HiveJobParameters struct {

	// Optional. Whether to continue executing queries if a query fails. The default value is `false`. Setting to `true` can be useful when executing independent parallel queries.
	// +kubebuilder:validation:Optional
	ContinueOnFailure *bool `json:"continueOnFailure,omitempty" tf:"continue_on_failure,omitempty"`

	// Optional. HCFS URIs of jar files to add to the CLASSPATH of the Hive server and Hadoop MapReduce (MR) tasks. Can contain Hive SerDes and UDFs.
	// +kubebuilder:validation:Optional
	JarFileUris []*string `json:"jarFileUris,omitempty" tf:"jar_file_uris,omitempty"`

	// Optional. A mapping of property names and values, used to configure Hive. Properties that conflict with values set by the Dataproc API may be overwritten. Can include properties set in /etc/hadoop/conf/*-site.xml, /etc/hive/conf/hive-site.xml, and classes in user code.
	// +kubebuilder:validation:Optional
	Properties map[string]*string `json:"properties,omitempty" tf:"properties,omitempty"`

	// The HCFS URI of the script that contains Hive queries.
	// +kubebuilder:validation:Optional
	QueryFileURI *string `json:"queryFileUri,omitempty" tf:"query_file_uri,omitempty"`

	// A list of queries.
	// +kubebuilder:validation:Optional
	QueryList []QueryListParameters `json:"queryList,omitempty" tf:"query_list,omitempty"`

	// Optional. Mapping of query variable names to values (equivalent to the Hive command: `SET name="value";`).
	// +kubebuilder:validation:Optional
	ScriptVariables map[string]*string `json:"scriptVariables,omitempty" tf:"script_variables,omitempty"`
}

type InitializationActionsObservation struct {
}

type InitializationActionsParameters struct {

	// Required. Cloud Storage URI of executable file.
	// +kubebuilder:validation:Optional
	ExecutableFile *string `json:"executableFile,omitempty" tf:"executable_file,omitempty"`

	// Optional. Amount of time executable has to complete. Default is 10 minutes (see JSON representation of [Duration](https://developers.google.com/protocol-buffers/docs/proto3#json)). Cluster creation fails with an explanatory error message (the name of the executable that caused the error and the exceeded timeout period) if the executable is not completed at end of the timeout period.
	// +kubebuilder:validation:Optional
	ExecutionTimeout *string `json:"executionTimeout,omitempty" tf:"execution_timeout,omitempty"`
}

type JobsObservation struct {
}

type JobsParameters struct {

	// Optional. Job is a Hadoop job.
	// +kubebuilder:validation:Optional
	HadoopJob []HadoopJobParameters `json:"hadoopJob,omitempty" tf:"hadoop_job,omitempty"`

	// Optional. Job is a Hive job.
	// +kubebuilder:validation:Optional
	HiveJob []HiveJobParameters `json:"hiveJob,omitempty" tf:"hive_job,omitempty"`

	// Optional. The labels to associate with this job. Label keys must be between 1 and 63 characters long, and must conform to the following regular expression: p{Ll}p{Lo}{0,62} Label values must be between 1 and 63 characters long, and must conform to the following regular expression: [p{Ll}p{Lo}p{N}_-]{0,63} No more than 32 labels can be associated with a given job.
	// +kubebuilder:validation:Optional
	Labels map[string]*string `json:"labels,omitempty" tf:"labels,omitempty"`

	// Optional. Job is a Pig job.
	// +kubebuilder:validation:Optional
	PigJob []PigJobParameters `json:"pigJob,omitempty" tf:"pig_job,omitempty"`

	// Optional. The optional list of prerequisite job step_ids. If not specified, the job will start at the beginning of workflow.
	// +kubebuilder:validation:Optional
	PrerequisiteStepIds []*string `json:"prerequisiteStepIds,omitempty" tf:"prerequisite_step_ids,omitempty"`

	// Optional. Job is a Presto job.
	// +kubebuilder:validation:Optional
	PrestoJob []PrestoJobParameters `json:"prestoJob,omitempty" tf:"presto_job,omitempty"`

	// Optional. Job is a PySpark job.
	// +kubebuilder:validation:Optional
	PysparkJob []PysparkJobParameters `json:"pysparkJob,omitempty" tf:"pyspark_job,omitempty"`

	// Optional. Job scheduling configuration.
	// +kubebuilder:validation:Optional
	Scheduling []JobsSchedulingParameters `json:"scheduling,omitempty" tf:"scheduling,omitempty"`

	// Optional. Job is a Spark job.
	// +kubebuilder:validation:Optional
	SparkJob []SparkJobParameters `json:"sparkJob,omitempty" tf:"spark_job,omitempty"`

	// Optional. Job is a SparkR job.
	// +kubebuilder:validation:Optional
	SparkRJob []SparkRJobParameters `json:"sparkRJob,omitempty" tf:"spark_r_job,omitempty"`

	// Optional. Job is a SparkSql job.
	// +kubebuilder:validation:Optional
	SparkSQLJob []SparkSQLJobParameters `json:"sparkSqlJob,omitempty" tf:"spark_sql_job,omitempty"`

	// Required. The step id. The id must be unique among all jobs within the template. The step id is used as prefix for job id, as job `goog-dataproc-workflow-step-id` label, and in prerequisiteStepIds field from other steps. The id must contain only letters (a-z, A-Z), numbers (0-9), underscores (_), and hyphens (-). Cannot begin or end with underscore or hyphen. Must consist of between 3 and 50 characters.
	// +kubebuilder:validation:Required
	StepID *string `json:"stepId" tf:"step_id,omitempty"`
}

type JobsSchedulingObservation struct {
}

type JobsSchedulingParameters struct {

	// Optional. Maximum number of times per hour a driver may be restarted as a result of driver exiting with non-zero code before job is reported failed. A job may be reported as thrashing if driver exits with non-zero code 4 times within 10 minute window. Maximum value is 10.
	// +kubebuilder:validation:Optional
	MaxFailuresPerHour *int64 `json:"maxFailuresPerHour,omitempty" tf:"max_failures_per_hour,omitempty"`

	// Optional. Maximum number of times in total a driver may be restarted as a result of driver exiting with non-zero code before job is reported failed. Maximum value is 240.
	// +kubebuilder:validation:Optional
	MaxFailuresTotal *int64 `json:"maxFailuresTotal,omitempty" tf:"max_failures_total,omitempty"`
}

type LifecycleConfigObservation struct {
	IdleStartTime *string `json:"idleStartTime,omitempty" tf:"idle_start_time,omitempty"`
}

type LifecycleConfigParameters struct {

	// Optional. The lifetime duration of cluster. The cluster will be auto-deleted at the end of this period. Minimum value is 10 minutes; maximum value is 14 days (see JSON representation of [Duration](https://developers.google.com/protocol-buffers/docs/proto3#json)).
	// +kubebuilder:validation:Optional
	AutoDeleteTTL *string `json:"autoDeleteTtl,omitempty" tf:"auto_delete_ttl,omitempty"`

	// Optional. The time when cluster will be auto-deleted (see JSON representation of [Timestamp](https://developers.google.com/protocol-buffers/docs/proto3#json)).
	// +kubebuilder:validation:Optional
	AutoDeleteTime *string `json:"autoDeleteTime,omitempty" tf:"auto_delete_time,omitempty"`

	// Optional. The duration to keep the cluster alive while idling (when no jobs are running). Passing this threshold will cause the cluster to be deleted. Minimum value is 5 minutes; maximum value is 14 days (see JSON representation of [Duration](https://developers.google.com/protocol-buffers/docs/proto3#json)).
	// +kubebuilder:validation:Optional
	IdleDeleteTTL *string `json:"idleDeleteTtl,omitempty" tf:"idle_delete_ttl,omitempty"`
}

type ManagedClusterObservation struct {
}

type ManagedClusterParameters struct {

	// Required. The cluster name prefix. A unique cluster name will be formed by appending a random suffix. The name must contain only lower-case letters (a-z), numbers (0-9), and hyphens (-). Must begin with a letter. Cannot begin or end with hyphen. Must consist of between 2 and 35 characters.
	// +kubebuilder:validation:Required
	ClusterName *string `json:"clusterName" tf:"cluster_name,omitempty"`

	// Required. The cluster configuration.
	// +kubebuilder:validation:Required
	Config []ConfigParameters `json:"config" tf:"config,omitempty"`

	// Optional. The labels to associate with this cluster. Label keys must be between 1 and 63 characters long, and must conform to the following PCRE regular expression: p{Ll}p{Lo}{0,62} Label values must be between 1 and 63 characters long, and must conform to the following PCRE regular expression: [p{Ll}p{Lo}p{N}_-]{0,63} No more than 32 labels can be associated with a given cluster.
	// +kubebuilder:validation:Optional
	Labels map[string]*string `json:"labels,omitempty" tf:"labels,omitempty"`
}

type ManagedGroupConfigObservation struct {
	InstanceGroupManagerName *string `json:"instanceGroupManagerName,omitempty" tf:"instance_group_manager_name,omitempty"`

	InstanceTemplateName *string `json:"instanceTemplateName,omitempty" tf:"instance_template_name,omitempty"`
}

type ManagedGroupConfigParameters struct {
}

type MasterConfigAcceleratorsObservation struct {
}

type MasterConfigAcceleratorsParameters struct {

	// The number of the accelerator cards of this type exposed to this instance.
	// +kubebuilder:validation:Optional
	AcceleratorCount *int64 `json:"acceleratorCount,omitempty" tf:"accelerator_count,omitempty"`

	// Full URL, partial URI, or short name of the accelerator type resource to expose to this instance. See [Compute Engine AcceleratorTypes](https://cloud.google.com/compute/docs/reference/beta/acceleratorTypes). Examples: * `https://www.googleapis.com/compute/beta/projects/[project_id]/zones/us-east1-a/acceleratorTypes/nvidia-tesla-k80` * `projects/[project_id]/zones/us-east1-a/acceleratorTypes/nvidia-tesla-k80` * `nvidia-tesla-k80` **Auto Zone Exception**: If you are using the Dataproc [Auto Zone Placement](https://cloud.google.com/dataproc/docs/concepts/configuring-clusters/auto-zone#using_auto_zone_placement) feature, you must use the short name of the accelerator type resource, for example, `nvidia-tesla-k80`.
	// +kubebuilder:validation:Optional
	AcceleratorType *string `json:"acceleratorType,omitempty" tf:"accelerator_type,omitempty"`
}

type MasterConfigDiskConfigObservation struct {
}

type MasterConfigDiskConfigParameters struct {

	// Optional. Size in GB of the boot disk (default is 500GB).
	// +kubebuilder:validation:Optional
	BootDiskSizeGb *int64 `json:"bootDiskSizeGb,omitempty" tf:"boot_disk_size_gb,omitempty"`

	// Optional. Type of the boot disk (default is "pd-standard"). Valid values: "pd-balanced" (Persistent Disk Balanced Solid State Drive), "pd-ssd" (Persistent Disk Solid State Drive), or "pd-standard" (Persistent Disk Hard Disk Drive). See [Disk types](https://cloud.google.com/compute/docs/disks#disk-types).
	// +kubebuilder:validation:Optional
	BootDiskType *string `json:"bootDiskType,omitempty" tf:"boot_disk_type,omitempty"`

	// Optional. Number of attached SSDs, from 0 to 4 (default is 0). If SSDs are not attached, the boot disk is used to store runtime logs and [HDFS](https://hadoop.apache.org/docs/r1.2.1/hdfs_user_guide.html) data. If one or more SSDs are attached, this runtime bulk data is spread across them, and the boot disk contains only basic config and installed binaries.
	// +kubebuilder:validation:Optional
	NumLocalSsds *int64 `json:"numLocalSsds,omitempty" tf:"num_local_ssds,omitempty"`
}

type NodeGroupAffinityObservation struct {
}

type NodeGroupAffinityParameters struct {

	// Required. The URI of a sole-tenant [node group resource](https://cloud.google.com/compute/docs/reference/rest/v1/nodeGroups) that the cluster will be created on. A full URL, partial URI, or node group name are valid. Examples: * `https://www.googleapis.com/compute/v1/projects/[project_id]/zones/us-central1-a/nodeGroups/node-group-1` * `projects/[project_id]/zones/us-central1-a/nodeGroups/node-group-1` * `node-group-1`
	// +kubebuilder:validation:Required
	NodeGroup *string `json:"nodeGroup" tf:"node_group,omitempty"`
}

type ParametersObservation struct {
}

type ParametersParameters struct {

	// Optional. Brief description of the parameter. Must not exceed 1024 characters.
	// +kubebuilder:validation:Optional
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// Required. Paths to all fields that the parameter replaces. A field is allowed to appear in at most one parameter's list of field paths. A field path is similar in syntax to a google.protobuf.FieldMask. For example, a field path that references the zone field of a workflow template's cluster selector would be specified as `placement.clusterSelector.zone`. Also, field paths can reference fields using the following syntax: * Values in maps can be referenced by key: * labels['key'] * placement.clusterSelector.clusterLabels['key'] * placement.managedCluster.labels['key'] * placement.clusterSelector.clusterLabels['key'] * jobs['step-id'].labels['key'] * Jobs in the jobs list can be referenced by step-id: * jobs['step-id'].hadoopJob.mainJarFileUri * jobs['step-id'].hiveJob.queryFileUri * jobs['step-id'].pySparkJob.mainPythonFileUri * jobs['step-id'].hadoopJob.jarFileUris[0] * jobs['step-id'].hadoopJob.archiveUris[0] * jobs['step-id'].hadoopJob.fileUris[0] * jobs['step-id'].pySparkJob.pythonFileUris[0] * Items in repeated fields can be referenced by a zero-based index: * jobs['step-id'].sparkJob.args[0] * Other examples: * jobs['step-id'].hadoopJob.properties['key'] * jobs['step-id'].hadoopJob.args[0] * jobs['step-id'].hiveJob.scriptVariables['key'] * jobs['step-id'].hadoopJob.mainJarFileUri * placement.clusterSelector.zone It may not be possible to parameterize maps and repeated fields in their entirety since only individual map values and individual items in repeated fields can be referenced. For example, the following field paths are invalid: - placement.clusterSelector.clusterLabels - jobs['step-id'].sparkJob.args
	// +kubebuilder:validation:Required
	Fields []*string `json:"fields" tf:"fields,omitempty"`

	// Required. Parameter name. The parameter name is used as the key, and paired with the parameter value, which are passed to the template when the template is instantiated. The name must contain only capital letters (A-Z), numbers (0-9), and underscores (_), and must not start with a number. The maximum length is 40 characters.
	// +kubebuilder:validation:Required
	Name *string `json:"name" tf:"name,omitempty"`

	// Optional. Validation rules to be applied to this parameter's value.
	// +kubebuilder:validation:Optional
	Validation []ValidationParameters `json:"validation,omitempty" tf:"validation,omitempty"`
}

type PigJobLoggingConfigObservation struct {
}

type PigJobLoggingConfigParameters struct {

	// The per-package log levels for the driver. This may include "root" package name to configure rootLogger. Examples: 'com.google = FATAL', 'root = INFO', 'org.apache = DEBUG'
	// +kubebuilder:validation:Optional
	DriverLogLevels map[string]*string `json:"driverLogLevels,omitempty" tf:"driver_log_levels,omitempty"`
}

type PigJobObservation struct {
}

type PigJobParameters struct {

	// Optional. Whether to continue executing queries if a query fails. The default value is `false`. Setting to `true` can be useful when executing independent parallel queries.
	// +kubebuilder:validation:Optional
	ContinueOnFailure *bool `json:"continueOnFailure,omitempty" tf:"continue_on_failure,omitempty"`

	// Optional. HCFS URIs of jar files to add to the CLASSPATH of the Pig Client and Hadoop MapReduce (MR) tasks. Can contain Pig UDFs.
	// +kubebuilder:validation:Optional
	JarFileUris []*string `json:"jarFileUris,omitempty" tf:"jar_file_uris,omitempty"`

	// Optional. The runtime log config for job execution.
	// +kubebuilder:validation:Optional
	LoggingConfig []PigJobLoggingConfigParameters `json:"loggingConfig,omitempty" tf:"logging_config,omitempty"`

	// Optional. A mapping of property names to values, used to configure Pig. Properties that conflict with values set by the Dataproc API may be overwritten. Can include properties set in /etc/hadoop/conf/*-site.xml, /etc/pig/conf/pig.properties, and classes in user code.
	// +kubebuilder:validation:Optional
	Properties map[string]*string `json:"properties,omitempty" tf:"properties,omitempty"`

	// The HCFS URI of the script that contains the Pig queries.
	// +kubebuilder:validation:Optional
	QueryFileURI *string `json:"queryFileUri,omitempty" tf:"query_file_uri,omitempty"`

	// A list of queries.
	// +kubebuilder:validation:Optional
	QueryList []PigJobQueryListParameters `json:"queryList,omitempty" tf:"query_list,omitempty"`

	// Optional. Mapping of query variable names to values (equivalent to the Pig command: `name=[value]`).
	// +kubebuilder:validation:Optional
	ScriptVariables map[string]*string `json:"scriptVariables,omitempty" tf:"script_variables,omitempty"`
}

type PigJobQueryListObservation struct {
}

type PigJobQueryListParameters struct {

	// Required. The queries to execute. You do not need to end a query expression with a semicolon. Multiple queries can be specified in one string by separating each with a semicolon. Here is an example of a Dataproc API snippet that uses a QueryList to specify a HiveJob: "hiveJob": { "queryList": { "queries": [ "query1", "query2", "query3;query4", ] } }
	// +kubebuilder:validation:Required
	Queries []*string `json:"queries" tf:"queries,omitempty"`
}

type PrestoJobLoggingConfigObservation struct {
}

type PrestoJobLoggingConfigParameters struct {

	// The per-package log levels for the driver. This may include "root" package name to configure rootLogger. Examples: 'com.google = FATAL', 'root = INFO', 'org.apache = DEBUG'
	// +kubebuilder:validation:Optional
	DriverLogLevels map[string]*string `json:"driverLogLevels,omitempty" tf:"driver_log_levels,omitempty"`
}

type PrestoJobObservation struct {
}

type PrestoJobParameters struct {

	// Optional. Presto client tags to attach to this query
	// +kubebuilder:validation:Optional
	ClientTags []*string `json:"clientTags,omitempty" tf:"client_tags,omitempty"`

	// Optional. Whether to continue executing queries if a query fails. The default value is `false`. Setting to `true` can be useful when executing independent parallel queries.
	// +kubebuilder:validation:Optional
	ContinueOnFailure *bool `json:"continueOnFailure,omitempty" tf:"continue_on_failure,omitempty"`

	// Optional. The runtime log config for job execution.
	// +kubebuilder:validation:Optional
	LoggingConfig []PrestoJobLoggingConfigParameters `json:"loggingConfig,omitempty" tf:"logging_config,omitempty"`

	// Optional. The format in which query output will be displayed. See the Presto documentation for supported output formats
	// +kubebuilder:validation:Optional
	OutputFormat *string `json:"outputFormat,omitempty" tf:"output_format,omitempty"`

	// Optional. A mapping of property names to values. Used to set Presto [session properties](https://prestodb.io/docs/current/sql/set-session.html) Equivalent to using the --session flag in the Presto CLI
	// +kubebuilder:validation:Optional
	Properties map[string]*string `json:"properties,omitempty" tf:"properties,omitempty"`

	// The HCFS URI of the script that contains SQL queries.
	// +kubebuilder:validation:Optional
	QueryFileURI *string `json:"queryFileUri,omitempty" tf:"query_file_uri,omitempty"`

	// A list of queries.
	// +kubebuilder:validation:Optional
	QueryList []PrestoJobQueryListParameters `json:"queryList,omitempty" tf:"query_list,omitempty"`
}

type PrestoJobQueryListObservation struct {
}

type PrestoJobQueryListParameters struct {

	// Required. The queries to execute. You do not need to end a query expression with a semicolon. Multiple queries can be specified in one string by separating each with a semicolon. Here is an example of a Dataproc API snippet that uses a QueryList to specify a HiveJob: "hiveJob": { "queryList": { "queries": [ "query1", "query2", "query3;query4", ] } }
	// +kubebuilder:validation:Required
	Queries []*string `json:"queries" tf:"queries,omitempty"`
}

type PysparkJobLoggingConfigObservation struct {
}

type PysparkJobLoggingConfigParameters struct {

	// The per-package log levels for the driver. This may include "root" package name to configure rootLogger. Examples: 'com.google = FATAL', 'root = INFO', 'org.apache = DEBUG'
	// +kubebuilder:validation:Optional
	DriverLogLevels map[string]*string `json:"driverLogLevels,omitempty" tf:"driver_log_levels,omitempty"`
}

type PysparkJobObservation struct {
}

type PysparkJobParameters struct {

	// Optional. HCFS URIs of archives to be extracted into the working directory of each executor. Supported file types: .jar, .tar, .tar.gz, .tgz, and .zip.
	// +kubebuilder:validation:Optional
	ArchiveUris []*string `json:"archiveUris,omitempty" tf:"archive_uris,omitempty"`

	// Optional. The arguments to pass to the driver. Do not include arguments, such as `--conf`, that can be set as job properties, since a collision may occur that causes an incorrect job submission.
	// +kubebuilder:validation:Optional
	Args []*string `json:"args,omitempty" tf:"args,omitempty"`

	// Optional. HCFS URIs of files to be placed in the working directory of each executor. Useful for naively parallel tasks.
	// +kubebuilder:validation:Optional
	FileUris []*string `json:"fileUris,omitempty" tf:"file_uris,omitempty"`

	// Optional. HCFS URIs of jar files to add to the CLASSPATHs of the Python driver and tasks.
	// +kubebuilder:validation:Optional
	JarFileUris []*string `json:"jarFileUris,omitempty" tf:"jar_file_uris,omitempty"`

	// Optional. The runtime log config for job execution.
	// +kubebuilder:validation:Optional
	LoggingConfig []PysparkJobLoggingConfigParameters `json:"loggingConfig,omitempty" tf:"logging_config,omitempty"`

	// Required. The HCFS URI of the main Python file to use as the driver. Must be a .py file.
	// +kubebuilder:validation:Required
	MainPythonFileURI *string `json:"mainPythonFileUri" tf:"main_python_file_uri,omitempty"`

	// Optional. A mapping of property names to values, used to configure PySpark. Properties that conflict with values set by the Dataproc API may be overwritten. Can include properties set in /etc/spark/conf/spark-defaults.conf and classes in user code.
	// +kubebuilder:validation:Optional
	Properties map[string]*string `json:"properties,omitempty" tf:"properties,omitempty"`

	// Optional. HCFS file URIs of Python files to pass to the PySpark framework. Supported file types: .py, .egg, and .zip.
	// +kubebuilder:validation:Optional
	PythonFileUris []*string `json:"pythonFileUris,omitempty" tf:"python_file_uris,omitempty"`
}

type QueryListObservation struct {
}

type QueryListParameters struct {

	// Required. The queries to execute. You do not need to end a query expression with a semicolon. Multiple queries can be specified in one string by separating each with a semicolon. Here is an example of a Dataproc API snippet that uses a QueryList to specify a HiveJob: "hiveJob": { "queryList": { "queries": [ "query1", "query2", "query3;query4", ] } }
	// +kubebuilder:validation:Required
	Queries []*string `json:"queries" tf:"queries,omitempty"`
}

type RegexObservation struct {
}

type RegexParameters struct {

	// Required. RE2 regular expressions used to validate the parameter's value. The value must match the regex in its entirety (substring matches are not sufficient).
	// +kubebuilder:validation:Required
	Regexes []*string `json:"regexes" tf:"regexes,omitempty"`
}

type ReservationAffinityObservation struct {
}

type ReservationAffinityParameters struct {

	// Optional. Type of reservation to consume Possible values: TYPE_UNSPECIFIED, NO_RESERVATION, ANY_RESERVATION, SPECIFIC_RESERVATION
	// +kubebuilder:validation:Optional
	ConsumeReservationType *string `json:"consumeReservationType,omitempty" tf:"consume_reservation_type,omitempty"`

	// Optional. Corresponds to the label key of reservation resource.
	// +kubebuilder:validation:Optional
	Key *string `json:"key,omitempty" tf:"key,omitempty"`

	// Optional. Corresponds to the label values of reservation resource.
	// +kubebuilder:validation:Optional
	Values []*string `json:"values,omitempty" tf:"values,omitempty"`
}

type SecondaryWorkerConfigAcceleratorsObservation struct {
}

type SecondaryWorkerConfigAcceleratorsParameters struct {

	// The number of the accelerator cards of this type exposed to this instance.
	// +kubebuilder:validation:Optional
	AcceleratorCount *int64 `json:"acceleratorCount,omitempty" tf:"accelerator_count,omitempty"`

	// Full URL, partial URI, or short name of the accelerator type resource to expose to this instance. See [Compute Engine AcceleratorTypes](https://cloud.google.com/compute/docs/reference/beta/acceleratorTypes). Examples: * `https://www.googleapis.com/compute/beta/projects/[project_id]/zones/us-east1-a/acceleratorTypes/nvidia-tesla-k80` * `projects/[project_id]/zones/us-east1-a/acceleratorTypes/nvidia-tesla-k80` * `nvidia-tesla-k80` **Auto Zone Exception**: If you are using the Dataproc [Auto Zone Placement](https://cloud.google.com/dataproc/docs/concepts/configuring-clusters/auto-zone#using_auto_zone_placement) feature, you must use the short name of the accelerator type resource, for example, `nvidia-tesla-k80`.
	// +kubebuilder:validation:Optional
	AcceleratorType *string `json:"acceleratorType,omitempty" tf:"accelerator_type,omitempty"`
}

type SecondaryWorkerConfigDiskConfigObservation struct {
}

type SecondaryWorkerConfigDiskConfigParameters struct {

	// Optional. Size in GB of the boot disk (default is 500GB).
	// +kubebuilder:validation:Optional
	BootDiskSizeGb *int64 `json:"bootDiskSizeGb,omitempty" tf:"boot_disk_size_gb,omitempty"`

	// Optional. Type of the boot disk (default is "pd-standard"). Valid values: "pd-balanced" (Persistent Disk Balanced Solid State Drive), "pd-ssd" (Persistent Disk Solid State Drive), or "pd-standard" (Persistent Disk Hard Disk Drive). See [Disk types](https://cloud.google.com/compute/docs/disks#disk-types).
	// +kubebuilder:validation:Optional
	BootDiskType *string `json:"bootDiskType,omitempty" tf:"boot_disk_type,omitempty"`

	// Optional. Number of attached SSDs, from 0 to 4 (default is 0). If SSDs are not attached, the boot disk is used to store runtime logs and [HDFS](https://hadoop.apache.org/docs/r1.2.1/hdfs_user_guide.html) data. If one or more SSDs are attached, this runtime bulk data is spread across them, and the boot disk contains only basic config and installed binaries.
	// +kubebuilder:validation:Optional
	NumLocalSsds *int64 `json:"numLocalSsds,omitempty" tf:"num_local_ssds,omitempty"`
}

type SecondaryWorkerConfigManagedGroupConfigObservation struct {
	InstanceGroupManagerName *string `json:"instanceGroupManagerName,omitempty" tf:"instance_group_manager_name,omitempty"`

	InstanceTemplateName *string `json:"instanceTemplateName,omitempty" tf:"instance_template_name,omitempty"`
}

type SecondaryWorkerConfigManagedGroupConfigParameters struct {
}

type SecurityConfigKerberosConfigObservation struct {
}

type SecurityConfigKerberosConfigParameters struct {

	// Optional. The admin server (IP or hostname) for the remote trusted realm in a cross realm trust relationship.
	// +kubebuilder:validation:Optional
	CrossRealmTrustAdminServer *string `json:"crossRealmTrustAdminServer,omitempty" tf:"cross_realm_trust_admin_server,omitempty"`

	// Optional. The KDC (IP or hostname) for the remote trusted realm in a cross realm trust relationship.
	// +kubebuilder:validation:Optional
	CrossRealmTrustKdc *string `json:"crossRealmTrustKdc,omitempty" tf:"cross_realm_trust_kdc,omitempty"`

	// Optional. The remote realm the Dataproc on-cluster KDC will trust, should the user enable cross realm trust.
	// +kubebuilder:validation:Optional
	CrossRealmTrustRealm *string `json:"crossRealmTrustRealm,omitempty" tf:"cross_realm_trust_realm,omitempty"`

	// Optional. The Cloud Storage URI of a KMS encrypted file containing the shared password between the on-cluster Kerberos realm and the remote trusted realm, in a cross realm trust relationship.
	// +kubebuilder:validation:Optional
	CrossRealmTrustSharedPassword *string `json:"crossRealmTrustSharedPassword,omitempty" tf:"cross_realm_trust_shared_password,omitempty"`

	// Optional. Flag to indicate whether to Kerberize the cluster (default: false). Set this field to true to enable Kerberos on a cluster.
	// +kubebuilder:validation:Optional
	EnableKerberos *bool `json:"enableKerberos,omitempty" tf:"enable_kerberos,omitempty"`

	// Optional. The Cloud Storage URI of a KMS encrypted file containing the master key of the KDC database.
	// +kubebuilder:validation:Optional
	KdcDBKey *string `json:"kdcDbKey,omitempty" tf:"kdc_db_key,omitempty"`

	// Optional. The Cloud Storage URI of a KMS encrypted file containing the password to the user provided key. For the self-signed certificate, this password is generated by Dataproc.
	// +kubebuilder:validation:Optional
	KeyPassword *string `json:"keyPassword,omitempty" tf:"key_password,omitempty"`

	// Optional. The Cloud Storage URI of the keystore file used for SSL encryption. If not provided, Dataproc will provide a self-signed certificate.
	// +kubebuilder:validation:Optional
	Keystore *string `json:"keystore,omitempty" tf:"keystore,omitempty"`

	// Optional. The Cloud Storage URI of a KMS encrypted file containing the password to the user provided keystore. For the self-signed certificate, this password is generated by Dataproc.
	// +kubebuilder:validation:Optional
	KeystorePassword *string `json:"keystorePassword,omitempty" tf:"keystore_password,omitempty"`

	// Optional. The uri of the KMS key used to encrypt various sensitive files.
	// +kubebuilder:validation:Optional
	KmsKey *string `json:"kmsKey,omitempty" tf:"kms_key,omitempty"`

	// Optional. The name of the on-cluster Kerberos realm. If not specified, the uppercased domain of hostnames will be the realm.
	// +kubebuilder:validation:Optional
	Realm *string `json:"realm,omitempty" tf:"realm,omitempty"`

	// Optional. The Cloud Storage URI of a KMS encrypted file containing the root principal password.
	// +kubebuilder:validation:Optional
	RootPrincipalPassword *string `json:"rootPrincipalPassword,omitempty" tf:"root_principal_password,omitempty"`

	// Optional. The lifetime of the ticket granting ticket, in hours. If not specified, or user specifies 0, then default value 10 will be used.
	// +kubebuilder:validation:Optional
	TgtLifetimeHours *int64 `json:"tgtLifetimeHours,omitempty" tf:"tgt_lifetime_hours,omitempty"`

	// Optional. The Cloud Storage URI of the truststore file used for SSL encryption. If not provided, Dataproc will provide a self-signed certificate.
	// +kubebuilder:validation:Optional
	Truststore *string `json:"truststore,omitempty" tf:"truststore,omitempty"`

	// Optional. The Cloud Storage URI of a KMS encrypted file containing the password to the user provided truststore. For the self-signed certificate, this password is generated by Dataproc.
	// +kubebuilder:validation:Optional
	TruststorePassword *string `json:"truststorePassword,omitempty" tf:"truststore_password,omitempty"`
}

type SparkJobLoggingConfigObservation struct {
}

type SparkJobLoggingConfigParameters struct {

	// The per-package log levels for the driver. This may include "root" package name to configure rootLogger. Examples: 'com.google = FATAL', 'root = INFO', 'org.apache = DEBUG'
	// +kubebuilder:validation:Optional
	DriverLogLevels map[string]*string `json:"driverLogLevels,omitempty" tf:"driver_log_levels,omitempty"`
}

type SparkJobObservation struct {
}

type SparkJobParameters struct {

	// Optional. HCFS URIs of archives to be extracted into the working directory of each executor. Supported file types: .jar, .tar, .tar.gz, .tgz, and .zip.
	// +kubebuilder:validation:Optional
	ArchiveUris []*string `json:"archiveUris,omitempty" tf:"archive_uris,omitempty"`

	// Optional. The arguments to pass to the driver. Do not include arguments, such as `--conf`, that can be set as job properties, since a collision may occur that causes an incorrect job submission.
	// +kubebuilder:validation:Optional
	Args []*string `json:"args,omitempty" tf:"args,omitempty"`

	// Optional. HCFS URIs of files to be placed in the working directory of each executor. Useful for naively parallel tasks.
	// +kubebuilder:validation:Optional
	FileUris []*string `json:"fileUris,omitempty" tf:"file_uris,omitempty"`

	// Optional. HCFS URIs of jar files to add to the CLASSPATHs of the Spark driver and tasks.
	// +kubebuilder:validation:Optional
	JarFileUris []*string `json:"jarFileUris,omitempty" tf:"jar_file_uris,omitempty"`

	// Optional. The runtime log config for job execution.
	// +kubebuilder:validation:Optional
	LoggingConfig []SparkJobLoggingConfigParameters `json:"loggingConfig,omitempty" tf:"logging_config,omitempty"`

	// The name of the driver's main class. The jar file that contains the class must be in the default CLASSPATH or specified in `jar_file_uris`.
	// +kubebuilder:validation:Optional
	MainClass *string `json:"mainClass,omitempty" tf:"main_class,omitempty"`

	// The HCFS URI of the jar file that contains the main class.
	// +kubebuilder:validation:Optional
	MainJarFileURI *string `json:"mainJarFileUri,omitempty" tf:"main_jar_file_uri,omitempty"`

	// Optional. A mapping of property names to values, used to configure Spark. Properties that conflict with values set by the Dataproc API may be overwritten. Can include properties set in /etc/spark/conf/spark-defaults.conf and classes in user code.
	// +kubebuilder:validation:Optional
	Properties map[string]*string `json:"properties,omitempty" tf:"properties,omitempty"`
}

type SparkRJobLoggingConfigObservation struct {
}

type SparkRJobLoggingConfigParameters struct {

	// The per-package log levels for the driver. This may include "root" package name to configure rootLogger. Examples: 'com.google = FATAL', 'root = INFO', 'org.apache = DEBUG'
	// +kubebuilder:validation:Optional
	DriverLogLevels map[string]*string `json:"driverLogLevels,omitempty" tf:"driver_log_levels,omitempty"`
}

type SparkRJobObservation struct {
}

type SparkRJobParameters struct {

	// Optional. HCFS URIs of archives to be extracted into the working directory of each executor. Supported file types: .jar, .tar, .tar.gz, .tgz, and .zip.
	// +kubebuilder:validation:Optional
	ArchiveUris []*string `json:"archiveUris,omitempty" tf:"archive_uris,omitempty"`

	// Optional. The arguments to pass to the driver. Do not include arguments, such as `--conf`, that can be set as job properties, since a collision may occur that causes an incorrect job submission.
	// +kubebuilder:validation:Optional
	Args []*string `json:"args,omitempty" tf:"args,omitempty"`

	// Optional. HCFS URIs of files to be placed in the working directory of each executor. Useful for naively parallel tasks.
	// +kubebuilder:validation:Optional
	FileUris []*string `json:"fileUris,omitempty" tf:"file_uris,omitempty"`

	// Optional. The runtime log config for job execution.
	// +kubebuilder:validation:Optional
	LoggingConfig []SparkRJobLoggingConfigParameters `json:"loggingConfig,omitempty" tf:"logging_config,omitempty"`

	// Required. The HCFS URI of the main R file to use as the driver. Must be a .R file.
	// +kubebuilder:validation:Required
	MainRFileURI *string `json:"mainRFileUri" tf:"main_r_file_uri,omitempty"`

	// Optional. A mapping of property names to values, used to configure SparkR. Properties that conflict with values set by the Dataproc API may be overwritten. Can include properties set in /etc/spark/conf/spark-defaults.conf and classes in user code.
	// +kubebuilder:validation:Optional
	Properties map[string]*string `json:"properties,omitempty" tf:"properties,omitempty"`
}

type SparkSQLJobLoggingConfigObservation struct {
}

type SparkSQLJobLoggingConfigParameters struct {

	// The per-package log levels for the driver. This may include "root" package name to configure rootLogger. Examples: 'com.google = FATAL', 'root = INFO', 'org.apache = DEBUG'
	// +kubebuilder:validation:Optional
	DriverLogLevels map[string]*string `json:"driverLogLevels,omitempty" tf:"driver_log_levels,omitempty"`
}

type SparkSQLJobObservation struct {
}

type SparkSQLJobParameters struct {

	// Optional. HCFS URIs of jar files to be added to the Spark CLASSPATH.
	// +kubebuilder:validation:Optional
	JarFileUris []*string `json:"jarFileUris,omitempty" tf:"jar_file_uris,omitempty"`

	// Optional. The runtime log config for job execution.
	// +kubebuilder:validation:Optional
	LoggingConfig []SparkSQLJobLoggingConfigParameters `json:"loggingConfig,omitempty" tf:"logging_config,omitempty"`

	// Optional. A mapping of property names to values, used to configure Spark SQL's SparkConf. Properties that conflict with values set by the Dataproc API may be overwritten.
	// +kubebuilder:validation:Optional
	Properties map[string]*string `json:"properties,omitempty" tf:"properties,omitempty"`

	// The HCFS URI of the script that contains SQL queries.
	// +kubebuilder:validation:Optional
	QueryFileURI *string `json:"queryFileUri,omitempty" tf:"query_file_uri,omitempty"`

	// A list of queries.
	// +kubebuilder:validation:Optional
	QueryList []SparkSQLJobQueryListParameters `json:"queryList,omitempty" tf:"query_list,omitempty"`

	// Optional. Mapping of query variable names to values (equivalent to the Spark SQL command: SET `name="value";`).
	// +kubebuilder:validation:Optional
	ScriptVariables map[string]*string `json:"scriptVariables,omitempty" tf:"script_variables,omitempty"`
}

type SparkSQLJobQueryListObservation struct {
}

type SparkSQLJobQueryListParameters struct {

	// Required. The queries to execute. You do not need to end a query expression with a semicolon. Multiple queries can be specified in one string by separating each with a semicolon. Here is an example of a Dataproc API snippet that uses a QueryList to specify a HiveJob: "hiveJob": { "queryList": { "queries": [ "query1", "query2", "query3;query4", ] } }
	// +kubebuilder:validation:Required
	Queries []*string `json:"queries" tf:"queries,omitempty"`
}

type ValidationObservation struct {
}

type ValidationParameters struct {

	// Validation based on regular expressions.
	// +kubebuilder:validation:Optional
	Regex []RegexParameters `json:"regex,omitempty" tf:"regex,omitempty"`

	// Validation based on a list of allowed values.
	// +kubebuilder:validation:Optional
	Values []ValuesParameters `json:"values,omitempty" tf:"values,omitempty"`
}

type ValuesObservation struct {
}

type ValuesParameters struct {

	// Required. List of allowed values for the parameter.
	// +kubebuilder:validation:Required
	Values []*string `json:"values" tf:"values,omitempty"`
}

type WorkerConfigManagedGroupConfigObservation struct {
	InstanceGroupManagerName *string `json:"instanceGroupManagerName,omitempty" tf:"instance_group_manager_name,omitempty"`

	InstanceTemplateName *string `json:"instanceTemplateName,omitempty" tf:"instance_template_name,omitempty"`
}

type WorkerConfigManagedGroupConfigParameters struct {
}

type WorkflowTemplateObservation struct {
	CreateTime *string `json:"createTime,omitempty" tf:"create_time,omitempty"`

	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	UpdateTime *string `json:"updateTime,omitempty" tf:"update_time,omitempty"`
}

type WorkflowTemplateParameters struct {

	// Optional. Timeout duration for the DAG of jobs, expressed in seconds (see [JSON representation of duration](https://developers.google.com/protocol-buffers/docs/proto3#json)). The timeout duration must be from 10 minutes ("600s") to 24 hours ("86400s"). The timer begins when the first job is submitted. If the workflow is running at the end of the timeout period, any remaining jobs are cancelled, the workflow is ended, and if the workflow was running on a [managed cluster](/dataproc/docs/concepts/workflows/using-workflows#configuring_or_selecting_a_cluster), the cluster is deleted.
	// +kubebuilder:validation:Optional
	DagTimeout *string `json:"dagTimeout,omitempty" tf:"dag_timeout,omitempty"`

	// Required. The Directed Acyclic Graph of Jobs to submit.
	// +kubebuilder:validation:Required
	Jobs []JobsParameters `json:"jobs" tf:"jobs,omitempty"`

	// Optional. The labels to associate with this template. These labels will be propagated to all jobs and clusters created by the workflow instance. Label **keys** must contain 1 to 63 characters, and must conform to [RFC 1035](https://www.ietf.org/rfc/rfc1035.txt). Label **values** may be empty, but, if present, must contain 1 to 63 characters, and must conform to [RFC 1035](https://www.ietf.org/rfc/rfc1035.txt). No more than 32 labels can be associated with a template.
	// +kubebuilder:validation:Optional
	Labels map[string]*string `json:"labels,omitempty" tf:"labels,omitempty"`

	// The location for the resource
	// +kubebuilder:validation:Required
	Location *string `json:"location" tf:"location,omitempty"`

	// Output only. The resource name of the workflow template, as described in https://cloud.google.com/apis/design/resource_names. * For `projects.regions.workflowTemplates`, the resource name of the template has the following format: `projects/{project_id}/regions/{region}/workflowTemplates/{template_id}` * For `projects.locations.workflowTemplates`, the resource name of the template has the following format: `projects/{project_id}/locations/{location}/workflowTemplates/{template_id}`
	// +kubebuilder:validation:Required
	Name *string `json:"name" tf:"name,omitempty"`

	// Optional. Template parameters whose values are substituted into the template. Values for parameters must be provided when the template is instantiated.
	// +kubebuilder:validation:Optional
	Parameters []ParametersParameters `json:"parameters,omitempty" tf:"parameters,omitempty"`

	// Required. WorkflowTemplate scheduling information.
	// +kubebuilder:validation:Required
	Placement []WorkflowTemplatePlacementParameters `json:"placement" tf:"placement,omitempty"`

	// The project for the resource
	// +kubebuilder:validation:Optional
	Project *string `json:"project,omitempty" tf:"project,omitempty"`

	// Output only. The current version of this workflow template.
	// +kubebuilder:validation:Optional
	Version *int64 `json:"version,omitempty" tf:"version,omitempty"`
}

type WorkflowTemplatePlacementObservation struct {
}

type WorkflowTemplatePlacementParameters struct {

	// Optional. A selector that chooses target cluster for jobs based on metadata. The selector is evaluated at the time each job is submitted.
	// +kubebuilder:validation:Optional
	ClusterSelector []ClusterSelectorParameters `json:"clusterSelector,omitempty" tf:"cluster_selector,omitempty"`

	// A cluster that is managed by the workflow.
	// +kubebuilder:validation:Optional
	ManagedCluster []ManagedClusterParameters `json:"managedCluster,omitempty" tf:"managed_cluster,omitempty"`
}

// WorkflowTemplateSpec defines the desired state of WorkflowTemplate
type WorkflowTemplateSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     WorkflowTemplateParameters `json:"forProvider"`
}

// WorkflowTemplateStatus defines the observed state of WorkflowTemplate.
type WorkflowTemplateStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        WorkflowTemplateObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true

// WorkflowTemplate is the Schema for the WorkflowTemplates API
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:subresource:status
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,gcpjet}
type WorkflowTemplate struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	Spec              WorkflowTemplateSpec   `json:"spec"`
	Status            WorkflowTemplateStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// WorkflowTemplateList contains a list of WorkflowTemplates
type WorkflowTemplateList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []WorkflowTemplate `json:"items"`
}

// Repository type metadata.
var (
	WorkflowTemplate_Kind             = "WorkflowTemplate"
	WorkflowTemplate_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: WorkflowTemplate_Kind}.String()
	WorkflowTemplate_KindAPIVersion   = WorkflowTemplate_Kind + "." + CRDGroupVersion.String()
	WorkflowTemplate_GroupVersionKind = CRDGroupVersion.WithKind(WorkflowTemplate_Kind)
)

func init() {
	SchemeBuilder.Register(&WorkflowTemplate{}, &WorkflowTemplateList{})
}
