apiVersion: secretmanager.gcp.jet.crossplane.io/v1alpha1
kind: Secret
metadata:
  name: example
spec:
  forProvider:
    labels:
      label: my-label
    replication:
    - userManaged:
      - replicas:
        - location: us-central1
        - location: us-east1
    secretId: secret
  providerConfigRef:
    name: example
