apiVersion: dataproc.gcp.jet.crossplane.io/v1alpha1
kind: Cluster
metadata:
  name: example
spec:
  forProvider:
    name: simplecluster
    region: us-central1
  providerConfigRef:
    name: example
