/*
Copyright 2021 The Crossplane Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by terrajet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/apis/common/v1"
)

type BucketIamPolicyObservation struct {
	Etag *string `json:"etag,omitempty" tf:"etag,omitempty"`

	ID *string `json:"id,omitempty" tf:"id,omitempty"`
}

type BucketIamPolicyParameters struct {

	// +kubebuilder:validation:Required
	Bucket *string `json:"bucket" tf:"bucket,omitempty"`

	// +kubebuilder:validation:Required
	PolicyData *string `json:"policyData" tf:"policy_data,omitempty"`
}

// BucketIamPolicySpec defines the desired state of BucketIamPolicy
type BucketIamPolicySpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     BucketIamPolicyParameters `json:"forProvider"`
}

// BucketIamPolicyStatus defines the observed state of BucketIamPolicy.
type BucketIamPolicyStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        BucketIamPolicyObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true

// BucketIamPolicy is the Schema for the BucketIamPolicys API
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:subresource:status
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,gcpjet}
type BucketIamPolicy struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	Spec              BucketIamPolicySpec   `json:"spec"`
	Status            BucketIamPolicyStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// BucketIamPolicyList contains a list of BucketIamPolicys
type BucketIamPolicyList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []BucketIamPolicy `json:"items"`
}

// Repository type metadata.
var (
	BucketIamPolicy_Kind             = "BucketIamPolicy"
	BucketIamPolicy_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: BucketIamPolicy_Kind}.String()
	BucketIamPolicy_KindAPIVersion   = BucketIamPolicy_Kind + "." + CRDGroupVersion.String()
	BucketIamPolicy_GroupVersionKind = CRDGroupVersion.WithKind(BucketIamPolicy_Kind)
)

func init() {
	SchemeBuilder.Register(&BucketIamPolicy{}, &BucketIamPolicyList{})
}
