apiVersion: bigtable.gcp.jet.crossplane.io/v1alpha1
kind: TableIamPolicy
metadata:
  name: example
spec:
  forProvider:
    instance: your-bigtable-instance
    policyData: ${data.google_iam_policy.admin.policy_data}
    project: your-project
    table: your-bigtable-table
  providerConfigRef:
    name: example
