apiVersion: sql.gcp.jet.crossplane.io/v1alpha1
kind: SslCert
metadata:
  name: example
spec:
  forProvider:
    commonName: client-name
    instance: hasan-testing-ssl-with-jet
  writeConnectionSecretToRef:
    name: sql-ssl-secret
    namespace: crossplane-system

