// +build !ignore_autogenerated

/*
Copyright 2021 The Crossplane Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AwsAccessKeyObservation) DeepCopyInto(out *AwsAccessKeyObservation) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AwsAccessKeyObservation.
func (in *AwsAccessKeyObservation) DeepCopy() *AwsAccessKeyObservation {
	if in == nil {
		return nil
	}
	out := new(AwsAccessKeyObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AwsAccessKeyParameters) DeepCopyInto(out *AwsAccessKeyParameters) {
	*out = *in
	out.AccessKeyIDSecretRef = in.AccessKeyIDSecretRef
	out.SecretAccessKeySecretRef = in.SecretAccessKeySecretRef
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AwsAccessKeyParameters.
func (in *AwsAccessKeyParameters) DeepCopy() *AwsAccessKeyParameters {
	if in == nil {
		return nil
	}
	out := new(AwsAccessKeyParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AwsS3DataSourceObservation) DeepCopyInto(out *AwsS3DataSourceObservation) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AwsS3DataSourceObservation.
func (in *AwsS3DataSourceObservation) DeepCopy() *AwsS3DataSourceObservation {
	if in == nil {
		return nil
	}
	out := new(AwsS3DataSourceObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AwsS3DataSourceParameters) DeepCopyInto(out *AwsS3DataSourceParameters) {
	*out = *in
	if in.AwsAccessKey != nil {
		in, out := &in.AwsAccessKey, &out.AwsAccessKey
		*out = make([]AwsAccessKeyParameters, len(*in))
		copy(*out, *in)
	}
	if in.BucketName != nil {
		in, out := &in.BucketName, &out.BucketName
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AwsS3DataSourceParameters.
func (in *AwsS3DataSourceParameters) DeepCopy() *AwsS3DataSourceParameters {
	if in == nil {
		return nil
	}
	out := new(AwsS3DataSourceParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AzureBlobStorageDataSourceObservation) DeepCopyInto(out *AzureBlobStorageDataSourceObservation) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AzureBlobStorageDataSourceObservation.
func (in *AzureBlobStorageDataSourceObservation) DeepCopy() *AzureBlobStorageDataSourceObservation {
	if in == nil {
		return nil
	}
	out := new(AzureBlobStorageDataSourceObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AzureBlobStorageDataSourceParameters) DeepCopyInto(out *AzureBlobStorageDataSourceParameters) {
	*out = *in
	if in.AzureCredentials != nil {
		in, out := &in.AzureCredentials, &out.AzureCredentials
		*out = make([]AzureCredentialsParameters, len(*in))
		copy(*out, *in)
	}
	if in.Container != nil {
		in, out := &in.Container, &out.Container
		*out = new(string)
		**out = **in
	}
	if in.Path != nil {
		in, out := &in.Path, &out.Path
		*out = new(string)
		**out = **in
	}
	if in.StorageAccount != nil {
		in, out := &in.StorageAccount, &out.StorageAccount
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AzureBlobStorageDataSourceParameters.
func (in *AzureBlobStorageDataSourceParameters) DeepCopy() *AzureBlobStorageDataSourceParameters {
	if in == nil {
		return nil
	}
	out := new(AzureBlobStorageDataSourceParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AzureCredentialsObservation) DeepCopyInto(out *AzureCredentialsObservation) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AzureCredentialsObservation.
func (in *AzureCredentialsObservation) DeepCopy() *AzureCredentialsObservation {
	if in == nil {
		return nil
	}
	out := new(AzureCredentialsObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AzureCredentialsParameters) DeepCopyInto(out *AzureCredentialsParameters) {
	*out = *in
	out.SasTokenSecretRef = in.SasTokenSecretRef
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AzureCredentialsParameters.
func (in *AzureCredentialsParameters) DeepCopy() *AzureCredentialsParameters {
	if in == nil {
		return nil
	}
	out := new(AzureCredentialsParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GcsDataSinkObservation) DeepCopyInto(out *GcsDataSinkObservation) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GcsDataSinkObservation.
func (in *GcsDataSinkObservation) DeepCopy() *GcsDataSinkObservation {
	if in == nil {
		return nil
	}
	out := new(GcsDataSinkObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GcsDataSinkParameters) DeepCopyInto(out *GcsDataSinkParameters) {
	*out = *in
	if in.BucketName != nil {
		in, out := &in.BucketName, &out.BucketName
		*out = new(string)
		**out = **in
	}
	if in.Path != nil {
		in, out := &in.Path, &out.Path
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GcsDataSinkParameters.
func (in *GcsDataSinkParameters) DeepCopy() *GcsDataSinkParameters {
	if in == nil {
		return nil
	}
	out := new(GcsDataSinkParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GcsDataSourceObservation) DeepCopyInto(out *GcsDataSourceObservation) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GcsDataSourceObservation.
func (in *GcsDataSourceObservation) DeepCopy() *GcsDataSourceObservation {
	if in == nil {
		return nil
	}
	out := new(GcsDataSourceObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GcsDataSourceParameters) DeepCopyInto(out *GcsDataSourceParameters) {
	*out = *in
	if in.BucketName != nil {
		in, out := &in.BucketName, &out.BucketName
		*out = new(string)
		**out = **in
	}
	if in.Path != nil {
		in, out := &in.Path, &out.Path
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GcsDataSourceParameters.
func (in *GcsDataSourceParameters) DeepCopy() *GcsDataSourceParameters {
	if in == nil {
		return nil
	}
	out := new(GcsDataSourceParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HTTPDataSourceObservation) DeepCopyInto(out *HTTPDataSourceObservation) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HTTPDataSourceObservation.
func (in *HTTPDataSourceObservation) DeepCopy() *HTTPDataSourceObservation {
	if in == nil {
		return nil
	}
	out := new(HTTPDataSourceObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HTTPDataSourceParameters) DeepCopyInto(out *HTTPDataSourceParameters) {
	*out = *in
	if in.ListURL != nil {
		in, out := &in.ListURL, &out.ListURL
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HTTPDataSourceParameters.
func (in *HTTPDataSourceParameters) DeepCopy() *HTTPDataSourceParameters {
	if in == nil {
		return nil
	}
	out := new(HTTPDataSourceParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Job) DeepCopyInto(out *Job) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Job.
func (in *Job) DeepCopy() *Job {
	if in == nil {
		return nil
	}
	out := new(Job)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Job) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *JobList) DeepCopyInto(out *JobList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Job, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new JobList.
func (in *JobList) DeepCopy() *JobList {
	if in == nil {
		return nil
	}
	out := new(JobList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *JobList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *JobObservation) DeepCopyInto(out *JobObservation) {
	*out = *in
	if in.CreationTime != nil {
		in, out := &in.CreationTime, &out.CreationTime
		*out = new(string)
		**out = **in
	}
	if in.DeletionTime != nil {
		in, out := &in.DeletionTime, &out.DeletionTime
		*out = new(string)
		**out = **in
	}
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.LastModificationTime != nil {
		in, out := &in.LastModificationTime, &out.LastModificationTime
		*out = new(string)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new JobObservation.
func (in *JobObservation) DeepCopy() *JobObservation {
	if in == nil {
		return nil
	}
	out := new(JobObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *JobParameters) DeepCopyInto(out *JobParameters) {
	*out = *in
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
	if in.Project != nil {
		in, out := &in.Project, &out.Project
		*out = new(string)
		**out = **in
	}
	if in.Schedule != nil {
		in, out := &in.Schedule, &out.Schedule
		*out = make([]ScheduleParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Status != nil {
		in, out := &in.Status, &out.Status
		*out = new(string)
		**out = **in
	}
	if in.TransferSpec != nil {
		in, out := &in.TransferSpec, &out.TransferSpec
		*out = make([]TransferSpecParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new JobParameters.
func (in *JobParameters) DeepCopy() *JobParameters {
	if in == nil {
		return nil
	}
	out := new(JobParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *JobSpec) DeepCopyInto(out *JobSpec) {
	*out = *in
	in.ResourceSpec.DeepCopyInto(&out.ResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new JobSpec.
func (in *JobSpec) DeepCopy() *JobSpec {
	if in == nil {
		return nil
	}
	out := new(JobSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *JobStatus) DeepCopyInto(out *JobStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new JobStatus.
func (in *JobStatus) DeepCopy() *JobStatus {
	if in == nil {
		return nil
	}
	out := new(JobStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ObjectConditionsObservation) DeepCopyInto(out *ObjectConditionsObservation) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ObjectConditionsObservation.
func (in *ObjectConditionsObservation) DeepCopy() *ObjectConditionsObservation {
	if in == nil {
		return nil
	}
	out := new(ObjectConditionsObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ObjectConditionsParameters) DeepCopyInto(out *ObjectConditionsParameters) {
	*out = *in
	if in.ExcludePrefixes != nil {
		in, out := &in.ExcludePrefixes, &out.ExcludePrefixes
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.IncludePrefixes != nil {
		in, out := &in.IncludePrefixes, &out.IncludePrefixes
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.MaxTimeElapsedSinceLastModification != nil {
		in, out := &in.MaxTimeElapsedSinceLastModification, &out.MaxTimeElapsedSinceLastModification
		*out = new(string)
		**out = **in
	}
	if in.MinTimeElapsedSinceLastModification != nil {
		in, out := &in.MinTimeElapsedSinceLastModification, &out.MinTimeElapsedSinceLastModification
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ObjectConditionsParameters.
func (in *ObjectConditionsParameters) DeepCopy() *ObjectConditionsParameters {
	if in == nil {
		return nil
	}
	out := new(ObjectConditionsParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ScheduleEndDateObservation) DeepCopyInto(out *ScheduleEndDateObservation) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ScheduleEndDateObservation.
func (in *ScheduleEndDateObservation) DeepCopy() *ScheduleEndDateObservation {
	if in == nil {
		return nil
	}
	out := new(ScheduleEndDateObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ScheduleEndDateParameters) DeepCopyInto(out *ScheduleEndDateParameters) {
	*out = *in
	if in.Day != nil {
		in, out := &in.Day, &out.Day
		*out = new(int64)
		**out = **in
	}
	if in.Month != nil {
		in, out := &in.Month, &out.Month
		*out = new(int64)
		**out = **in
	}
	if in.Year != nil {
		in, out := &in.Year, &out.Year
		*out = new(int64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ScheduleEndDateParameters.
func (in *ScheduleEndDateParameters) DeepCopy() *ScheduleEndDateParameters {
	if in == nil {
		return nil
	}
	out := new(ScheduleEndDateParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ScheduleObservation) DeepCopyInto(out *ScheduleObservation) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ScheduleObservation.
func (in *ScheduleObservation) DeepCopy() *ScheduleObservation {
	if in == nil {
		return nil
	}
	out := new(ScheduleObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ScheduleParameters) DeepCopyInto(out *ScheduleParameters) {
	*out = *in
	if in.ScheduleEndDate != nil {
		in, out := &in.ScheduleEndDate, &out.ScheduleEndDate
		*out = make([]ScheduleEndDateParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ScheduleStartDate != nil {
		in, out := &in.ScheduleStartDate, &out.ScheduleStartDate
		*out = make([]ScheduleStartDateParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.StartTimeOfDay != nil {
		in, out := &in.StartTimeOfDay, &out.StartTimeOfDay
		*out = make([]StartTimeOfDayParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ScheduleParameters.
func (in *ScheduleParameters) DeepCopy() *ScheduleParameters {
	if in == nil {
		return nil
	}
	out := new(ScheduleParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ScheduleStartDateObservation) DeepCopyInto(out *ScheduleStartDateObservation) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ScheduleStartDateObservation.
func (in *ScheduleStartDateObservation) DeepCopy() *ScheduleStartDateObservation {
	if in == nil {
		return nil
	}
	out := new(ScheduleStartDateObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ScheduleStartDateParameters) DeepCopyInto(out *ScheduleStartDateParameters) {
	*out = *in
	if in.Day != nil {
		in, out := &in.Day, &out.Day
		*out = new(int64)
		**out = **in
	}
	if in.Month != nil {
		in, out := &in.Month, &out.Month
		*out = new(int64)
		**out = **in
	}
	if in.Year != nil {
		in, out := &in.Year, &out.Year
		*out = new(int64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ScheduleStartDateParameters.
func (in *ScheduleStartDateParameters) DeepCopy() *ScheduleStartDateParameters {
	if in == nil {
		return nil
	}
	out := new(ScheduleStartDateParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StartTimeOfDayObservation) DeepCopyInto(out *StartTimeOfDayObservation) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StartTimeOfDayObservation.
func (in *StartTimeOfDayObservation) DeepCopy() *StartTimeOfDayObservation {
	if in == nil {
		return nil
	}
	out := new(StartTimeOfDayObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StartTimeOfDayParameters) DeepCopyInto(out *StartTimeOfDayParameters) {
	*out = *in
	if in.Hours != nil {
		in, out := &in.Hours, &out.Hours
		*out = new(int64)
		**out = **in
	}
	if in.Minutes != nil {
		in, out := &in.Minutes, &out.Minutes
		*out = new(int64)
		**out = **in
	}
	if in.Nanos != nil {
		in, out := &in.Nanos, &out.Nanos
		*out = new(int64)
		**out = **in
	}
	if in.Seconds != nil {
		in, out := &in.Seconds, &out.Seconds
		*out = new(int64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StartTimeOfDayParameters.
func (in *StartTimeOfDayParameters) DeepCopy() *StartTimeOfDayParameters {
	if in == nil {
		return nil
	}
	out := new(StartTimeOfDayParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TransferOptionsObservation) DeepCopyInto(out *TransferOptionsObservation) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TransferOptionsObservation.
func (in *TransferOptionsObservation) DeepCopy() *TransferOptionsObservation {
	if in == nil {
		return nil
	}
	out := new(TransferOptionsObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TransferOptionsParameters) DeepCopyInto(out *TransferOptionsParameters) {
	*out = *in
	if in.DeleteObjectsFromSourceAfterTransfer != nil {
		in, out := &in.DeleteObjectsFromSourceAfterTransfer, &out.DeleteObjectsFromSourceAfterTransfer
		*out = new(bool)
		**out = **in
	}
	if in.DeleteObjectsUniqueInSink != nil {
		in, out := &in.DeleteObjectsUniqueInSink, &out.DeleteObjectsUniqueInSink
		*out = new(bool)
		**out = **in
	}
	if in.OverwriteObjectsAlreadyExistingInSink != nil {
		in, out := &in.OverwriteObjectsAlreadyExistingInSink, &out.OverwriteObjectsAlreadyExistingInSink
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TransferOptionsParameters.
func (in *TransferOptionsParameters) DeepCopy() *TransferOptionsParameters {
	if in == nil {
		return nil
	}
	out := new(TransferOptionsParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TransferSpecObservation) DeepCopyInto(out *TransferSpecObservation) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TransferSpecObservation.
func (in *TransferSpecObservation) DeepCopy() *TransferSpecObservation {
	if in == nil {
		return nil
	}
	out := new(TransferSpecObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TransferSpecParameters) DeepCopyInto(out *TransferSpecParameters) {
	*out = *in
	if in.AwsS3DataSource != nil {
		in, out := &in.AwsS3DataSource, &out.AwsS3DataSource
		*out = make([]AwsS3DataSourceParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.AzureBlobStorageDataSource != nil {
		in, out := &in.AzureBlobStorageDataSource, &out.AzureBlobStorageDataSource
		*out = make([]AzureBlobStorageDataSourceParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.GcsDataSink != nil {
		in, out := &in.GcsDataSink, &out.GcsDataSink
		*out = make([]GcsDataSinkParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.GcsDataSource != nil {
		in, out := &in.GcsDataSource, &out.GcsDataSource
		*out = make([]GcsDataSourceParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.HTTPDataSource != nil {
		in, out := &in.HTTPDataSource, &out.HTTPDataSource
		*out = make([]HTTPDataSourceParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ObjectConditions != nil {
		in, out := &in.ObjectConditions, &out.ObjectConditions
		*out = make([]ObjectConditionsParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.TransferOptions != nil {
		in, out := &in.TransferOptions, &out.TransferOptions
		*out = make([]TransferOptionsParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TransferSpecParameters.
func (in *TransferSpecParameters) DeepCopy() *TransferSpecParameters {
	if in == nil {
		return nil
	}
	out := new(TransferSpecParameters)
	in.DeepCopyInto(out)
	return out
}
