apiVersion: iap.gcp.jet.crossplane.io/v1alpha1
kind: TunnelInstanceIamPolicy
metadata:
  name: example
spec:
  forProvider:
    instance: ${google_compute_instance.tunnelvm.name}
    policyData: ${data.google_iam_policy.admin.policy_data}
    project: ${google_compute_instance.tunnelvm.project}
    zone: us-central1-a
  providerConfigRef:
    name: example
