apiVersion: iap.gcp.jet.crossplane.io/v1alpha1
kind: WebBackendServiceIamPolicy
metadata:
  name: example
spec:
  forProvider:
    policyData: ${data.google_iam_policy.admin.policy_data}
    project: ${google_compute_backend_service.default.project}
    webBackendService: backend-service
  providerConfigRef:
    name: example
