apiVersion: notebooks.gcp.jet.crossplane.io/v1alpha1
kind: Instance
metadata:
  name: example
spec:
  forProvider:
    location: us-west1-a
    machineType: e2-medium
    name: notebooks-instance
    vmImage:
    - imageFamily: tf-latest-cpu
      project: deeplearning-platform-release
  providerConfigRef:
    name: example
