apiVersion: monitoring.gcp.jet.crossplane.io/v1alpha1
kind: Group
metadata:
  name: example
spec:
  forProvider:
    displayName: tf-test MonitoringGroup
    filter: resource.metadata.region="europe-west2"
  providerConfigRef:
    name: example
