apiVersion: dialogflow.gcp.jet.crossplane.io/v1alpha1
kind: CxEntityType
metadata:
  name: example
spec:
  forProvider:
    displayName: MyEntity
    enableFuzzyExtraction: false
    entities:
    - synonyms:
      - synonym1
      - synonym2
      value: value1
    - synonyms:
      - synonym3
      - synonym4
      value: value2
    kind: KIND_MAP
    parent: ${google_dialogflow_cx_agent.agent.id}
  providerConfigRef:
    name: example
