/*
Copyright 2021 The Crossplane Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by terrajet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/apis/common/v1"
)

type WebTypeComputeIAMPolicyObservation struct {
	Etag *string `json:"etag,omitempty" tf:"etag,omitempty"`

	ID *string `json:"id,omitempty" tf:"id,omitempty"`
}

type WebTypeComputeIAMPolicyParameters struct {

	// +kubebuilder:validation:Required
	PolicyData *string `json:"policyData" tf:"policy_data,omitempty"`

	// +kubebuilder:validation:Optional
	Project *string `json:"project,omitempty" tf:"project,omitempty"`
}

// WebTypeComputeIAMPolicySpec defines the desired state of WebTypeComputeIAMPolicy
type WebTypeComputeIAMPolicySpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     WebTypeComputeIAMPolicyParameters `json:"forProvider"`
}

// WebTypeComputeIAMPolicyStatus defines the observed state of WebTypeComputeIAMPolicy.
type WebTypeComputeIAMPolicyStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        WebTypeComputeIAMPolicyObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true

// WebTypeComputeIAMPolicy is the Schema for the WebTypeComputeIAMPolicys API
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:subresource:status
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,gcpjet}
type WebTypeComputeIAMPolicy struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	Spec              WebTypeComputeIAMPolicySpec   `json:"spec"`
	Status            WebTypeComputeIAMPolicyStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// WebTypeComputeIAMPolicyList contains a list of WebTypeComputeIAMPolicys
type WebTypeComputeIAMPolicyList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []WebTypeComputeIAMPolicy `json:"items"`
}

// Repository type metadata.
var (
	WebTypeComputeIAMPolicy_Kind             = "WebTypeComputeIAMPolicy"
	WebTypeComputeIAMPolicy_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: WebTypeComputeIAMPolicy_Kind}.String()
	WebTypeComputeIAMPolicy_KindAPIVersion   = WebTypeComputeIAMPolicy_Kind + "." + CRDGroupVersion.String()
	WebTypeComputeIAMPolicy_GroupVersionKind = CRDGroupVersion.WithKind(WebTypeComputeIAMPolicy_Kind)
)

func init() {
	SchemeBuilder.Register(&WebTypeComputeIAMPolicy{}, &WebTypeComputeIAMPolicyList{})
}
