apiVersion: container.gcp.jet.crossplane.io/v1alpha1
kind: AnalysisNote
metadata:
  name: example
spec:
  forProvider:
    attestationAuthority:
    - hint:
      - humanReadableName: Attestor Note
    name: attestor-note
  providerConfigRef:
    name: example
