apiVersion: container.gcp.jet.crossplane.io/v1alpha1
kind: Cluster
metadata:
  name: example
spec:
  forProvider:
    initialNodeCount: 1
    location: us-central1
    name: my-gke-cluster
    removeDefaultNodePool: true
  providerConfigRef:
    name: example
