apiVersion: cloudtasks.gcp.jet.crossplane.io/v1alpha1
kind: Queue
metadata:
  name: example
spec:
  forProvider:
    location: us-central1
    name: cloud-tasks-queue-test
  providerConfigRef:
    name: example
