apiVersion: identityplatform.gcp.jet.crossplane.io/v1alpha1
kind: Tenant
metadata:
  name: example
spec:
  forProvider:
    allowPasswordSignup: true
    displayName: tenant
  providerConfigRef:
    name: example
