apiVersion: sql.gcp.jet.crossplane.io/v1alpha1
kind: User
metadata:
  name: example
spec:
  forProvider:
    host: me.com
    instance: master-instance
    name: me
    passwordSecretRef:
      key: example-key
      name: example-secret
      namespace: crossplane-system
  providerConfigRef:
    name: example
