apiVersion: dns.gcp.jet.crossplane.io/v1alpha1
kind: ManagedZone
metadata:
  name: example
spec:
  forProvider:
    description: Example DNS zone
    dnsName: example-${random_id.rnd.hex}.com.
    labels:
      foo: bar
    name: example-zone
  providerConfigRef:
    name: example
