apiVersion: cloudplatform.gcp.jet.crossplane.io/v1alpha1
kind: ServiceAccount
metadata:
  name: example
spec:
  forProvider:
    accountId: service-account-id
    displayName: Service Account
  providerConfigRef:
    name: example
