apiVersion: gameservices.gcp.jet.crossplane.io/v1alpha1
kind: Realm
metadata:
  name: example
spec:
  forProvider:
    description: one of the nine
    location: global
    realmId: tf-test-realm
    timeZone: EST
  providerConfigRef:
    name: example
