apiVersion: essentialcontacts.gcp.jet.crossplane.io/v1alpha1
kind: Contact
metadata:
  name: example
spec:
  forProvider:
    email: foo@bar.com
    languageTag: en-GB
    notificationCategorySubscriptions:
    - ALL
    parent: ${data.google_project.project.id}
  providerConfigRef:
    name: example
