apiVersion: cloudiot.gcp.jet.crossplane.io/v1alpha1
kind: Device
metadata:
  name: example
spec:
  forProvider:
    name: cloudiot-device
    registry: ${google_cloudiot_registry.registry.id}
  providerConfigRef:
    name: example
