apiVersion: compute.gcp.jet.crossplane.io/v1alpha1
kind: Autoscaler
metadata:
  name: example
spec:
  forProvider:
    autoscalingPolicy:
    - cooldownPeriod: 60
      maxReplicas: 5
      metric:
      - filter: resource.type = pubsub_subscription AND resource.label.subscription_id
          = our-subscription
        name: pubsub.googleapis.com/subscription/num_undelivered_messages
        single_instance_assignment: 65535
      minReplicas: 1
    name: my-autoscaler
    provider: ${google-beta}
    target: ${google_compute_instance_group_manager.default.id}
    zone: us-central1-f
  providerConfigRef:
    name: example
