apiVersion: compute.gcp.jet.crossplane.io/v1alpha1
kind: BackendService
metadata:
  name: example
spec:
  forProvider:
    healthChecks:
    - ${google_compute_http_health_check.default.id}
    name: backend-service
  providerConfigRef:
    name: example
