apiVersion: compute.gcp.jet.crossplane.io/v1alpha1
kind: ExternalVpnGateway
metadata:
  name: example
spec:
  forProvider:
    description: An externally managed VPN gateway
    interface:
    - id: 0
      ipAddress: 8.8.8.8
    name: external-gateway
    redundancyType: SINGLE_IP_INTERNALLY_REDUNDANT
  providerConfigRef:
    name: example
