apiVersion: compute.gcp.jet.crossplane.io/v1alpha1
kind: Firewall
metadata:
  name: example
spec:
  forProvider:
    allow:
    - protocol: icmp
    - ports:
      - "80"
      - "8080"
      - 1000-2000
      protocol: tcp
    networkRef:
      name: example
    sourceTags:
    - web
  providerConfigRef:
    name: example
