apiVersion: compute.gcp.jet.crossplane.io/v1alpha1
kind: ManagedSSLCertificate
metadata:
  name: example
spec:
  forProvider:
    managed:
    - domains:
      - sslcert.tf-test.club.
  providerConfigRef:
    name: example
