apiVersion: compute.gcp.jet.crossplane.io/v1alpha1
kind: RouterNat
metadata:
  name: example
spec:
  forProvider:
    logConfig:
    - enable: true
      filter: ERRORS_ONLY
    natIpAllocateOption: AUTO_ONLY
    region: ${google_compute_router.router.region}
    routerRef:
      name: example
    sourceSubnetworkIpRangesToNat: ALL_SUBNETWORKS_ALL_IP_RANGES
  providerConfigRef:
    name: example
