apiVersion: compute.gcp.jet.crossplane.io/v1alpha1
kind: RouterPeer
metadata:
  name: example
spec:
  forProvider:
    advertisedRoutePriority: 100
    interface: interface-1
    name: my-router-peer
    peerAsn: 65513
    peerIpAddress: 169.254.1.2
    region: us-central1
    router: my-router
  providerConfigRef:
    name: example
