apiVersion: compute.gcp.jet.crossplane.io/v1alpha1
kind: TargetGrpcProxy
metadata:
  name: example
spec:
  forProvider:
    name: proxy
    urlMap: ${google_compute_url_map.urlmap.id}
    validateForProxyless: true
  providerConfigRef:
    name: example
